table 2026-2
	lineageTag: b26d4ab7-80b2-4625-a783-b252ec6a50a5

	column Unidade
		dataType: string
		lineageTag: 04d8d286-00e8-46b0-9535-9d60dc549aa8
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Tabulação já foi realizada?'
		dataType: string
		lineageTag: d770ff6f-a3ce-4513-b251-5c4d43e5f082
		summarizeBy: none
		sourceColumn: Tabulação já foi realizada?

		annotation SummarizationSetBy = Automatic

	column 'UTM Content'
		dataType: string
		lineageTag: 0c7148ce-339d-4b87-9ecb-72aed3a839f8
		summarizeBy: none
		sourceColumn: UTM Content

		annotation SummarizationSetBy = Automatic

	column 'UTM Medium'
		dataType: string
		lineageTag: beaa997b-e09a-4e16-bc81-141de82cad86
		summarizeBy: none
		sourceColumn: UTM Medium

		annotation SummarizationSetBy = Automatic

	column 'UTM Name'
		dataType: string
		lineageTag: df3e55c3-bd05-46b8-a67e-1f6f35aee2d0
		summarizeBy: none
		sourceColumn: UTM Name

		annotation SummarizationSetBy = Automatic

	column 'UTM Source'
		dataType: string
		lineageTag: eaac35c6-401c-48d8-b987-b9be49649f9c
		summarizeBy: none
		sourceColumn: UTM Source

		annotation SummarizationSetBy = Automatic

	column 'UTM Term'
		dataType: string
		lineageTag: a27c4ad2-1988-49cb-896d-c4e40a785b24
		summarizeBy: none
		sourceColumn: UTM Term

		annotation SummarizationSetBy = Automatic

	column 'result.address1_addressid'
		dataType: string
		lineageTag: 9ec74251-235a-497c-9e38-decf80c48050
		summarizeBy: none
		sourceColumn: result.address1_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.cad_browser'
		dataType: string
		lineageTag: 5ee89838-dcbd-4562-8896-7c0389d245ec
		summarizeBy: none
		sourceColumn: result.cad_browser

		annotation SummarizationSetBy = Automatic

	column 'result.address2_addressid'
		dataType: string
		lineageTag: 07d03861-83b1-4a2f-9dd5-c16ed4041cbb
		summarizeBy: none
		sourceColumn: result.address2_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.crmeduc_unidadeform'
		dataType: string
		lineageTag: 900be8f9-cc41-4ac5-a135-36b9af4ff1d1
		summarizeBy: none
		sourceColumn: result.crmeduc_unidadeform

		annotation SummarizationSetBy = Automatic

	column 'Concurso Atual Corrigido'
		dataType: string
		lineageTag: 49c28fa1-47da-480b-bdc9-7ab38c538ba9
		summarizeBy: none
		sourceColumn: Concurso Atual Corrigido

		annotation SummarizationSetBy = Automatic

	column 'Concurso Origem Corrigido'
		dataType: string
		lineageTag: 9f01a8af-5130-4fea-9969-118be9afea0d
		summarizeBy: none
		sourceColumn: Concurso Origem Corrigido

		annotation SummarizationSetBy = Automatic

	column 'Forma de Ingresso'
		dataType: string
		lineageTag: 150ce07d-c5a5-44f3-9fdf-6221e2c83a91
		summarizeBy: none
		sourceColumn: Forma de Ingresso

		annotation SummarizationSetBy = Automatic

	column 'Curso ID'
		dataType: string
		lineageTag: 719cd24e-5106-42e6-9676-dec1b4a9a2d8
		summarizeBy: none
		sourceColumn: Curso ID

		annotation SummarizationSetBy = Automatic

	column 'Situação Inscrição'
		dataType: string
		lineageTag: 30b867ec-cbe1-490e-8865-a6d8396e837d
		summarizeBy: none
		sourceColumn: Situação Inscrição

		annotation SummarizationSetBy = Automatic

	column 'Situação de Avaliação'
		dataType: string
		lineageTag: d7a75cd8-08de-4c39-b396-d8fb0d3d9722
		summarizeBy: none
		sourceColumn: Situação de Avaliação

		annotation SummarizationSetBy = Automatic

	column 'Unidade Inscrito'
		dataType: string
		lineageTag: e8e9ad4d-4952-415a-acdb-4adf637458f8
		summarizeBy: none
		sourceColumn: Unidade Inscrito

		annotation SummarizationSetBy = Automatic

	column 'Situação Pagamento'
		dataType: string
		lineageTag: c4f09524-37f7-4af9-8514-5c9ac16ba20e
		summarizeBy: none
		sourceColumn: Situação Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Data de Pagamento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: efd4497b-e2dd-4ae3-935a-a52cf17b9606
		summarizeBy: none
		sourceColumn: Data de Pagamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Curso Unidade'
		dataType: string
		lineageTag: 9c3458c9-a087-4c77-8db7-c38e6e72ae6a
		summarizeBy: none
		sourceColumn: Curso Unidade

		annotation SummarizationSetBy = Automatic

	column 'Celular Comparar Legado'
		dataType: string
		lineageTag: e26c8a99-a8b8-4381-9300-c6ff20067a8c
		summarizeBy: none
		sourceColumn: Celular Comparar Legado

		annotation SummarizationSetBy = Automatic

	column Legado
		dataType: string
		lineageTag: c37bca83-4916-4e9b-a12a-81330ebb39f4
		summarizeBy: none
		sourceColumn: Legado

		annotation SummarizationSetBy = Automatic

	column 'Aging Matricula' = ```
			
			
			VAR Diferenca = 
			DATEDIFF(
			'2026-2'[Data Criacao],
			'2026-2'[Data de Pagamento],
			DAY
			)
			
			RETURN
			IF(
			    Diferenca < 0, 0, Diferenca)
			
			
			
			```
		formatString: 0
		lineageTag: 532241cc-1dbf-4c41-97e2-d54e19b65856
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Aging Faixa' = ```
			
			    SWITCH(
			        TRUE(),
			        '2026-2'[Aging Matricula] >= 90 , "+90" ,
			        '2026-2'[Aging Matricula] >= 60 , "+60" ,
			        '2026-2'[Aging Matricula] >= 30 , "+30" ,
			        '2026-2'[Aging Matricula] >= 15 , "+15" ,
			        '2026-2'[Aging Matricula] >= 7 , "+7" ,
			        '2026-2'[Aging Matricula] > 1 , "+1" ,
			        '2026-2'[Aging Matricula] <= 1 , "0" ,
			        BLANK()
			    )
			
			```
		lineageTag: 98c783d9-1785-40f8-ad50-ac7bbb028660
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Última Tabulação'
		dataType: string
		lineageTag: 27792e7c-47c2-46a8-8171-353cbbae2da0
		summarizeBy: none
		sourceColumn: Última Tabulação

		annotation SummarizationSetBy = Automatic

	column 'result.trivento_unidadetrivento'
		dataType: string
		lineageTag: 081b5d94-1ed2-4fe1-a8ac-5edb1b21aa84
		summarizeBy: none
		sourceColumn: result.trivento_unidadetrivento

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 3d1f54f9-9c05-444c-9054-3a15b2c5173b
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column CPF
		dataType: string
		lineageTag: 85c6f272-dd31-4fe0-944a-e06808fba892
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: b2dd69d1-30d0-4275-b2c7-ec0ac8808da8
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Sobrenome
		dataType: string
		lineageTag: f6419e62-1251-4fc8-9868-7c5f36db7538
		summarizeBy: none
		sourceColumn: Sobrenome

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 1b9783d3-db64-462c-9b44-f33606875dee
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: string
		lineageTag: 43474447-d4e9-43d6-a8d5-76c0baa51162
		summarizeBy: none
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column 'Celular 2'
		dataType: string
		lineageTag: 49e7a456-eef9-4910-b128-162e29109a14
		summarizeBy: none
		sourceColumn: Celular 2

		annotation SummarizationSetBy = Automatic

	column 'ID Lead'
		dataType: string
		lineageTag: 306eabff-1c61-4c51-b988-9bb443b76d2c
		summarizeBy: none
		sourceColumn: ID Lead

		annotation SummarizationSetBy = Automatic

	column 'Data Criacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c3dbad5-704a-4acb-86c4-22c24d431f7e
		summarizeBy: none
		sourceColumn: Data Criacao

		variation Variation
			isDefault
			relationship: 463a0ef1-da88-4daf-bcac-d31dd58faf1a
			defaultHierarchy: LocalDateTable_902ee6ed-8382-4f35-ada4-1a52b6b1f630.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cidade
		dataType: string
		lineageTag: f40788f6-13e0-43a1-bdd3-7aa4c19ed22e
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Endereço
		dataType: string
		lineageTag: 581b013c-adc7-47fe-b3ef-e6c2b022a069
		summarizeBy: none
		sourceColumn: Endereço

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: c09b4293-8551-4dc8-be83-3df969daee03
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: 96b73a01-35fd-4a0c-80f4-437466b269ef
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Rua
		dataType: string
		lineageTag: 4b0ad387-59d1-487b-bbda-86c4125d38d8
		summarizeBy: none
		sourceColumn: Rua

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4463956f-5205-4301-a7be-e242e29cabbc
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: 914a084f-0ebb-4334-8140-52e7347e81e4
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: 7355ee76-ec2a-4f4f-ae7a-751d5f06bc63
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 9108f429-0a3c-4fb4-887d-947802967dca
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: string
		lineageTag: d3aa97f6-431a-441f-a63e-6b29add97d29
		summarizeBy: none
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column 'Data Aceite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1d71ef28-1b43-4801-805b-f55168b41965
		summarizeBy: none
		sourceColumn: Data Aceite

		variation Variation
			isDefault
			relationship: 637d05f9-c569-48fa-80d3-6ec22aec1a5a
			defaultHierarchy: LocalDateTable_42ef74b0-3334-4660-9dc5-a97982b3bbe8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data alteração'
		dataType: dateTime
		formatString: General Date
		lineageTag: b8c66153-01c3-4662-a09e-585e164ffd58
		summarizeBy: none
		sourceColumn: Data alteração

		variation Variation
			isDefault
			relationship: faa36547-76a2-458f-a364-0f4606a207c8
			defaultHierarchy: LocalDateTable_e59bd786-d20d-4986-86bc-7b325c2afab5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: string
		lineageTag: 4c5b7a5f-5a8f-4da3-938b-f3f1a266587d
		summarizeBy: none
		sourceColumn: Data Nascimento

		annotation SummarizationSetBy = Automatic

	column 'Numero Inscricao'
		dataType: string
		lineageTag: 66c2377a-f6cd-405b-834c-1a02f290ffa1
		summarizeBy: none
		sourceColumn: Numero Inscricao

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: 4b690ee4-86f5-427e-8088-483575d0a0fb
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column 'Situacao Funil'
		dataType: string
		lineageTag: 9030d902-75d0-446f-94d7-a348bcdcaf8b
		summarizeBy: none
		sourceColumn: Situacao Funil

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead'
		dataType: string
		lineageTag: b176d23c-dce2-449d-9642-c18a91ba2f27
		summarizeBy: none
		sourceColumn: Origem Lead

		annotation SummarizationSetBy = Automatic

	column 'Linha de Negócio'
		dataType: string
		lineageTag: 452424c4-3525-41c9-a32d-be7af54c35b5
		summarizeBy: none
		sourceColumn: Linha de Negócio

		annotation SummarizationSetBy = Automatic

	column 'Proprietário Lead'
		dataType: string
		lineageTag: 0764e20d-3ccb-4634-b031-91d3ab9c8149
		summarizeBy: none
		sourceColumn: Proprietário Lead

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead ID'
		dataType: string
		lineageTag: 785888e6-1683-493b-abcf-5d80841137d4
		summarizeBy: none
		sourceColumn: Origem Lead ID

		annotation SummarizationSetBy = Automatic

	column Attribute:name
		dataType: string
		lineageTag: 2b827074-fe16-4ef0-9830-d75bdf4879e3
		summarizeBy: none
		sourceColumn: Attribute:name

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: fe46e35b-be5a-4582-b6b7-efd0f9f7d8e3
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column 'Orgao Expedidor'
		dataType: string
		lineageTag: 4b6b669f-4318-4872-a45d-d4836567fbe6
		summarizeBy: none
		sourceColumn: Orgao Expedidor

		annotation SummarizationSetBy = Automatic

	column RG
		dataType: string
		lineageTag: f4166110-61a4-4893-8588-8d5ed397f3c3
		summarizeBy: none
		sourceColumn: RG

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 8793dd40-0096-4aef-af95-8309e0c26820
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column Cor
		dataType: string
		lineageTag: 76f4851b-8ac1-411f-9056-2f8a743d0192
		summarizeBy: none
		sourceColumn: Cor

		annotation SummarizationSetBy = Automatic

	column Tabulação
		dataType: string
		lineageTag: 0d4ba974-865a-46be-8f48-0b72fa8f9937
		summarizeBy: none
		sourceColumn: Tabulação

		annotation SummarizationSetBy = Automatic

	column 'Tabulação Detalhe'
		dataType: string
		lineageTag: ae4d88ca-9a35-4108-bf7e-cfcc1cd67dba
		summarizeBy: none
		sourceColumn: Tabulação Detalhe

		annotation SummarizationSetBy = Automatic

	partition 2026-2 = m
		mode: import
		queryGroup: 'Consultas - Token'
		source = ```
				let
				    Fonte = Leads,
				    #"Personalização Adicionada" = Table.AddColumn(Fonte, "Concurso Atual Corrigido", each Text.Trim(Text.BeforeDelimiter([Concurso Atual], " -"))),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Concurso Origem Corrigido", each Text.Trim(Text.BeforeDelimiter([Concurso Origem], "-"))),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Personalização Adicionada1", {"Concurso Atual", "Concurso Origem"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas1", {{"result.cad_campaigncontent", "UTM Content"}, {"result.cad_campaignmedium", "UTM Medium"}, {"result.cad_campaignname", "UTM Name"}, {"result.cad_campaignsource", "UTM Source"}, {"result.cad_campaignterm", "UTM Term"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"Numero Inscricao"}, Inscricoes, {"result.cad_numeroinscricao"}, "Inscricoes", JoinKind.LeftOuter),
				    #"Inscricoes Expandido1" = Table.ExpandTableColumn(#"Consultas Mescladas", "Inscricoes", {"Forma de Ingresso", "Curso ID", "Situação Inscrição", "Situação de Avaliação", "Unidade Inscrito", "Situação Pagamento", "Data de Pagamento"}, {"Forma de Ingresso", "Curso ID", "Situação Inscrição", "Situação de Avaliação", "Unidade Inscrito", "Situação Pagamento", "Data de Pagamento"}),
				    #"Unidade Original Removida" = Table.RemoveColumns(#"Inscricoes Expandido1", {"Unidade"}),
				    #"Unidade Definida" = Table.AddColumn(#"Unidade Original Removida", "Unidade", each 
				        if [result.trivento_unidadetrivento] <> null and Text.Trim(Text.From([result.trivento_unidadetrivento])) <> "" then 
				            [result.trivento_unidadetrivento] 
				        else 
				            [result.crmeduc_unidadeform]
				    ),
				    #"Valor Substituído" = Table.ReplaceValue(#"Unidade Definida","Canaa","Canaã",Replacer.ReplaceText,{"Unidade"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído",{{"Unidade", Text.Proper, type text}}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula",",","",Replacer.ReplaceText,{"Endereço"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",null,"Lead",Replacer.ReplaceValue,{"Situação Inscrição"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2","ADMINISTRAÇÃO","Administração",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","Análise de Desenvolvimento de Sistemas","Análise e Desenvolvimento de Sistemas",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","EDUCAÇÃO FÍSICA","Educação Física",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído5","Educação Fisica","Educação Física",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído6","Odontoligia","Odontologia",Replacer.ReplaceText,{"Curso ID"}),
				    #"Curso Unidade Adicionado" = Table.AddColumn(#"Valor Substituído7", "Curso Unidade", each [Unidade Inscrito] & "-" & [Curso ID]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Curso Unidade Adicionado",{{"Curso Unidade", type text}}),
				    #"Valor Substituído8" = Table.ReplaceValue(#"Tipo Alterado"," -","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído9" = Table.ReplaceValue(#"Valor Substituído8","-","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído10" = Table.ReplaceValue(#"Valor Substituído9"," Faculdade Serra Dourada Altamira","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído11" = Table.ReplaceValue(#"Valor Substituído10"," Faculdade Serra Dourada Canaã","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído12" = Table.ReplaceValue(#"Valor Substituído11"," Faculdade Serra Dourada Lorena","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído13" = Table.ReplaceValue(#"Valor Substituído12"," Faculdade Alis","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído14" = Table.ReplaceValue(#"Valor Substituído13","Concurso de Bolsas ","Concurso de Bolsas",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído14",{{"Unidade", type text}}),
				    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado1", "Celular Comparar Legado", each "+55" & Text.Replace(Text.Replace(Text.Replace(Text.Replace([Celular], "(", ""), ")", ""), "-", ""), " ", "")),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada3",{{"Celular Comparar Legado", type text}}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Tipo Alterado2", {"Celular Comparar Legado"}, Legado, {"Celular"}, "Legado", JoinKind.LeftOuter),
				    #"Legado Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "Legado", {"Legado"}, {"Legado.1"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Legado Expandido",{{"Legado.1", "Legado"}}),
				    #"Valor Substituído15" = Table.ReplaceValue(#"Colunas Renomeadas2",null,"Ciclo Atual",Replacer.ReplaceValue,{"Legado"}),
				    #"Valor Substituído16" = Table.ReplaceValue(#"Valor Substituído15","{","",Replacer.ReplaceText,{"ID Lead"}),
				    #"Valor Substituído17" = Table.ReplaceValue(#"Valor Substituído16","}","",Replacer.ReplaceText,{"ID Lead"}),
				    #"Não é Cursos Livres" = Table.SelectRows(#"Valor Substituído17", each ([Unidade] <> "Cursos Livres Altamira" and [Unidade] <> "Cursos Livres Lorena")),
				    #"Ajuste Odonto" = Table.ReplaceValue(#"Não é Cursos Livres","Odontoligia","Odontologia",Replacer.ReplaceText,{"Curso"}),
				    #"Ajuste Fisio" = Table.ReplaceValue(#"Ajuste Odonto","Fisioterapia ","Fisioterapia",Replacer.ReplaceText,{"Curso ID"}),
				    #"Ajuste Mecânica" = Table.ReplaceValue(#"Ajuste Fisio","Engenharia Macânica","Engenharia Mecânica",Replacer.ReplaceText,{"Curso ID"}),
				    #"Ajuste Ed Física" = Table.ReplaceValue(#"Ajuste Mecânica","Educação Fisica","Educação Física",Replacer.ReplaceText,{"Curso"}),
				    #"Ajuste Ed Física 2" = Table.ReplaceValue(#"Ajuste Ed Física","EDUCAÇÃO FÍSICA","Educação Física",Replacer.ReplaceText,{"Curso"}),
				    #"Ajuste Biomed" = Table.ReplaceValue(#"Ajuste Ed Física 2","Bomedicina","Biomedicina",Replacer.ReplaceText,{"Curso ID"}),
				    #"Ajuste ADS" = Table.ReplaceValue(#"Ajuste Biomed","Análise de Desenvolvimento de Sistemas","Análise e Desenvolvimento de Sistemas",Replacer.ReplaceText,{"Curso"}),
				    #"Ajuste Agro" = Table.ReplaceValue(#"Ajuste ADS","Agronomia ","Agronomia",Replacer.ReplaceText,{"Curso ID"}),
				    #"Ajuste ADM" = Table.ReplaceValue(#"Ajuste Agro","ADMINISTRAÇÃO","Administração",Replacer.ReplaceText,{"Curso"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Ajuste ADM", {"ID Lead"})
				in
				    #"Duplicatas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

