table 2026-2
	lineageTag: 7627338a-87e4-413f-a001-aade7071e225

	column 'Numero Inscricao'
		dataType: string
		lineageTag: 7ffae10a-fe56-48ba-9895-3ffee68651c6
		summarizeBy: none
		sourceColumn: Numero Inscricao

		annotation SummarizationSetBy = Automatic

	column 'Concurso Atual Corrigido'
		dataType: string
		lineageTag: 826922a0-fb2f-4aec-a1df-8eb5ba79340d
		summarizeBy: none
		sourceColumn: Concurso Atual Corrigido

		annotation SummarizationSetBy = Automatic

	column 'Concurso Origem Corrigido'
		dataType: string
		lineageTag: ad853adc-8a7b-4455-8cad-aab79f56a96f
		summarizeBy: none
		sourceColumn: Concurso Origem Corrigido

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: string
		lineageTag: 112cb269-6b44-41a3-84cc-46ee287775a3
		summarizeBy: none
		sourceColumn: Data Nascimento

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: 7ceea338-c185-49a0-a53c-a1b149c3f323
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column 'Situacao Funil'
		dataType: string
		lineageTag: df9990c2-f89c-42a9-a872-f2ee15712262
		summarizeBy: none
		sourceColumn: Situacao Funil

		annotation SummarizationSetBy = Automatic

	column 'Data Criacao'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 72ac3120-050f-4daa-bfd8-9c39b0504fd3
		summarizeBy: none
		sourceColumn: Data Criacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Idade
		dataType: string
		lineageTag: 1a32e67b-cfed-4f20-8c9a-671e2b707355
		summarizeBy: none
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column 'Unidade Lead'
		dataType: string
		lineageTag: 095df802-c2be-4208-976b-2e06164bcd0e
		summarizeBy: none
		sourceColumn: Unidade Lead

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 07cb77d0-df81-4481-b95f-6ce9234eb695
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: ef7be070-f4fb-43f0-bceb-410b8c95d5a9
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 739171f0-4d76-4f2e-9828-7a43c95c9a71
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column Sobrenome
		dataType: string
		lineageTag: 8e14b969-61c3-4b31-8186-1378695c4ab3
		summarizeBy: none
		sourceColumn: Sobrenome

		annotation SummarizationSetBy = Automatic

	column 'ID Lead'
		dataType: string
		lineageTag: 1559dbe0-ff6e-4403-858d-0f9fe235d377
		summarizeBy: none
		sourceColumn: ID Lead

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead'
		dataType: string
		lineageTag: 6a2aa835-0c0e-4cda-92c6-cf91cbf67b0b
		summarizeBy: none
		sourceColumn: Origem Lead

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: string
		lineageTag: f96d09d1-3284-48ee-b4c9-03de905feb14
		summarizeBy: none
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 2c7b0de6-4523-4ee6-ae90-b89bd4188015
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Celular 2'
		dataType: string
		lineageTag: ca3a6fa7-ef97-4cfe-bb18-5073fc0192f3
		summarizeBy: none
		sourceColumn: Celular 2

		annotation SummarizationSetBy = Automatic

	column 'Linha de Negócio'
		dataType: string
		lineageTag: 9decc6b2-d218-4627-a753-f3ea3b83ff5c
		summarizeBy: none
		sourceColumn: Linha de Negócio

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 252d082a-d132-461a-9521-8c02c5ddb134
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Endereço
		dataType: string
		lineageTag: 2b5b5f25-4b3a-49b4-beac-cf50e9c2e59c
		summarizeBy: none
		sourceColumn: Endereço

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 6681d5cd-d907-49de-b0f4-90bdb1358188
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: 64fa4578-9ebf-4d31-984b-743b28237018
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Rua
		dataType: string
		lineageTag: 1617618a-b5c0-45e5-a4fa-9e3c79a9c59b
		summarizeBy: none
		sourceColumn: Rua

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: ca78eeb0-b802-49b6-8fb9-9f29540e7487
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: 9254a54b-2c3f-4d89-92e4-a46fa2bad11a
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 747882df-4f20-4a57-beda-1133f53da2f6
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column Cor
		dataType: string
		lineageTag: 0923e46e-8ea0-411e-94b8-3abe54aa09d8
		summarizeBy: none
		sourceColumn: Cor

		annotation SummarizationSetBy = Automatic

	column 'Orgao Expedidor'
		dataType: string
		lineageTag: 74f0ea39-f5dd-4570-8908-ea767fb2bb41
		summarizeBy: none
		sourceColumn: Orgao Expedidor

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: bdb80a89-cad9-43b0-af8f-41bc4b609110
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column RG
		dataType: string
		lineageTag: 4ded906b-628f-431b-85d9-f6f3100d30f1
		summarizeBy: none
		sourceColumn: RG

		annotation SummarizationSetBy = Automatic

	column Attribute:name
		dataType: string
		lineageTag: ef853a3f-8e6d-44ea-9848-99b3555bef59
		summarizeBy: none
		sourceColumn: Attribute:name

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead ID'
		dataType: string
		lineageTag: bbfcb46c-0f59-4a46-88c5-33cb092c04ee
		summarizeBy: none
		sourceColumn: Origem Lead ID

		annotation SummarizationSetBy = Automatic

	column 'Data de Pagamento'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a8ad309f-b43d-4eed-be56-49182ad9b1c1
		summarizeBy: none
		sourceColumn: Data de Pagamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Aceite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 836754f1-2483-485e-9075-970c9f604728
		summarizeBy: none
		sourceColumn: Data Aceite

		variation Variation
			isDefault
			relationship: 225c04b2-de35-4337-badc-3a1eb3931844
			defaultHierarchy: LocalDateTable_c9677879-e2e5-4e7e-b6a4-9df7c68af34f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data alteração'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c4577ed-8c23-41d5-9fd9-57e805a1b9d0
		summarizeBy: none
		sourceColumn: Data alteração

		variation Variation
			isDefault
			relationship: b7223b55-7286-4879-8929-80344f8598a6
			defaultHierarchy: LocalDateTable_da4f0d9b-3d82-4f38-855c-fa47d98a0950.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tabulação Detalhe'
		dataType: string
		lineageTag: 63915ca1-7977-412a-a2cd-5ac692d43cf9
		summarizeBy: none
		sourceColumn: Tabulação Detalhe

		annotation SummarizationSetBy = Automatic

	column 'result.crmeduc_unidadeform'
		dataType: string
		lineageTag: 0660a9e2-dbb9-4871-90bd-d37a13d2b3f3
		summarizeBy: none
		sourceColumn: result.crmeduc_unidadeform

		annotation SummarizationSetBy = Automatic

	column 'UTM Content'
		dataType: string
		lineageTag: 8426a2c3-a738-42d7-acca-0b7547e5a165
		summarizeBy: none
		sourceColumn: UTM Content

		annotation SummarizationSetBy = Automatic

	column 'UTM Medium'
		dataType: string
		lineageTag: 2f5c4ef3-9c21-46b8-89d2-6f534bfd0853
		summarizeBy: none
		sourceColumn: UTM Medium

		annotation SummarizationSetBy = Automatic

	column 'UTM Name'
		dataType: string
		lineageTag: 9d186909-85f8-408d-a02e-753ba8787d8b
		summarizeBy: none
		sourceColumn: UTM Name

		annotation SummarizationSetBy = Automatic

	column 'UTM Source'
		dataType: string
		lineageTag: 92f08488-3a68-4511-b269-e8e613e6e152
		summarizeBy: none
		sourceColumn: UTM Source

		annotation SummarizationSetBy = Automatic

	column 'UTM Term'
		dataType: string
		lineageTag: b942512d-b18e-4a99-9558-22b0a8a4b7f6
		summarizeBy: none
		sourceColumn: UTM Term

		annotation SummarizationSetBy = Automatic

	column 'Curso Unidade'
		dataType: string
		lineageTag: 34dc464a-e099-44f0-ae47-9080056056e5
		summarizeBy: none
		sourceColumn: Curso Unidade

		annotation SummarizationSetBy = Automatic

	column Tabulação
		dataType: string
		lineageTag: 994d12e6-a47e-4a99-a977-d9921a678784
		summarizeBy: none
		sourceColumn: Tabulação

		annotation SummarizationSetBy = Automatic

	column 'Proprietário Lead'
		dataType: string
		lineageTag: ca130910-84ca-4f56-97c1-9bcde813e187
		summarizeBy: none
		sourceColumn: Proprietário Lead

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: 739cf5f0-c5b9-4c03-b3a8-af1269c2f0ac
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column 'Data Aprovação'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e5956b42-2e88-4de6-8ea9-4fefb1352935
		summarizeBy: none
		sourceColumn: Data Aprovação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'result.address1_addressid'
		dataType: string
		lineageTag: 818219c0-b9c9-4b4f-abfa-4f14c2d306fc
		summarizeBy: none
		sourceColumn: result.address1_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.address2_addressid'
		dataType: string
		lineageTag: e80c7c58-fa61-418c-aa4c-a727b70880e4
		summarizeBy: none
		sourceColumn: result.address2_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.cad_browser'
		dataType: string
		lineageTag: 4ae6af2a-3468-4d60-b9ae-5f32cae1e8b2
		summarizeBy: none
		sourceColumn: result.cad_browser

		annotation SummarizationSetBy = Automatic

	column 'Curso ID'
		dataType: string
		lineageTag: 4c05b7a9-57e1-48ac-97ab-a97aa790d4d1
		summarizeBy: none
		sourceColumn: Curso ID

		annotation SummarizationSetBy = Automatic

	column 'Situação Inscrição'
		dataType: string
		lineageTag: 302ae123-87e5-4a08-888a-b5daf6fd0764
		summarizeBy: none
		sourceColumn: Situação Inscrição

		annotation SummarizationSetBy = Automatic

	column 'Unidade Inscrito'
		dataType: string
		lineageTag: 052025d3-09fd-4cc5-8b2a-74e8b720eca4
		summarizeBy: none
		sourceColumn: Unidade Inscrito

		annotation SummarizationSetBy = Automatic

	column 'Situação de Avaliação'
		dataType: string
		lineageTag: e4bb9a62-16b6-4cfb-b018-8799df9edb60
		summarizeBy: none
		sourceColumn: Situação de Avaliação

		annotation SummarizationSetBy = Automatic

	column 'Forma de Ingresso'
		dataType: string
		lineageTag: 8a037f54-85c7-484b-99e5-68c26a26a7d6
		summarizeBy: none
		sourceColumn: Forma de Ingresso

		annotation SummarizationSetBy = Automatic

	column 'Tabulação já foi realizada?'
		dataType: string
		lineageTag: d899f5a3-d723-46a3-83e6-35c8412d1b26
		summarizeBy: none
		sourceColumn: Tabulação já foi realizada?

		annotation SummarizationSetBy = Automatic

	column 'Última Tabulação'
		dataType: string
		lineageTag: 0eae91a6-ec4e-4943-bb6d-f47e3899b9b0
		summarizeBy: none
		sourceColumn: Última Tabulação

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 0cdbbdc3-67b4-4f96-accc-94cb35c7eaeb
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Aging Matrícula' = ```
			
			    DATEDIFF(
			        '2026-2'[Data Criacao],
			        '2026-2'[Data de Pagamento],
			        DAY
			    )
			```
		formatString: 0
		lineageTag: 5a60687c-2491-4cf9-92a6-7639cffcc0f3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Aging Faixa' = ```
			
			    SWITCH(
			        TRUE(),
			        '2026-2'[Aging Matrícula] >= 90 , "+90" ,
			        '2026-2'[Aging Matrícula] >= 60 , "+60" ,
			        '2026-2'[Aging Matrícula] >= 30 , "+30" ,
			        '2026-2'[Aging Matrícula] >= 15 , "+15" ,
			        '2026-2'[Aging Matrícula] >= 7 , "+7" ,
			        '2026-2'[Aging Matrícula] > 1 , "+1" ,
			        '2026-2'[Aging Matrícula] <= 1 , "0" ,
			        BLANK()
			    )
			
			```
		lineageTag: cdaf5c4e-9465-4b9c-9285-5faf8ae28393
		summarizeBy: none
		sortByColumn: 'Aging Faixa Ordem'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Aging Faixa Ordem' = ```
			
			    SWITCH(
			        TRUE(),
			        '2026-2'[Aging Matrícula] >= 90 , "6" ,
			        '2026-2'[Aging Matrícula] >= 60 , "5" ,
			        '2026-2'[Aging Matrícula] >= 30 , "4" ,
			        '2026-2'[Aging Matrícula] >= 15 , "3" ,
			        '2026-2'[Aging Matrícula] >= 7 , "2" ,
			        '2026-2'[Aging Matrícula] > 1 , "1" ,
			        '2026-2'[Aging Matrícula] <= 1 , "0" ,
			        BLANK()
			    )
			
			```
		lineageTag: 0d5b3200-78c2-4000-bb9f-8b211ed26841
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Filtro Medicina' = ```
			
			    SWITCH(
			        TRUE(),
			        '2026-2'[Curso ID] = "Medicina" , "Medicina" , 
			        "Demais Cursos"
			    )
			```
		lineageTag: 3f260716-8165-410d-9a14-0e33b33cdd80
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Situação Pagamento'
		dataType: string
		lineageTag: 0a10dd92-6c77-4f24-abe2-9ec7d21b7b1f
		summarizeBy: none
		sourceColumn: Situação Pagamento

		annotation SummarizationSetBy = Automatic

	partition 2026-2 = m
		mode: import
		queryGroup: 'Consultas - Token'
		source = ```
				let
				    Fonte = Leads,
				    #"Personalização Adicionada" = Table.AddColumn(
				        Fonte,
				        "Concurso Atual Corrigido",
				        each Text.Trim(Text.BeforeDelimiter([Concurso Atual], " -"))
				    ),
				    
				    #"Personalização Adicionada1" = Table.AddColumn(
				        #"Personalização Adicionada",
				        "Concurso Origem Corrigido",
				        each Text.Trim(Text.BeforeDelimiter([Concurso Origem], "-"))
				    ),
				    
				    #"Colunas Removidas1" = Table.RemoveColumns(
				        #"Personalização Adicionada1",
				        {"Concurso Atual", "Concurso Origem"}
				    ),
				    
				    #"Unidade Corrigida" = Table.ReplaceValue(
				    #"Colunas Removidas1",
				    each [Unidade],
				    each
				        if [Unidade] = null or [Unidade] = "" then
				            
				            // Primeiro tenta pegar da coluna result.crmeduc_unidadeform
				            if [result.crmeduc_unidadeform] <> null 
				                and Text.Trim(Text.From([result.crmeduc_unidadeform])) <> "" then
				                    [result.crmeduc_unidadeform]
				
				            // Se não tiver, tenta pegar da coluna result.trivento_unidadetrivento
				            else if [result.trivento_unidadetrivento] <> null
				                and Text.Trim(Text.From([result.trivento_unidadetrivento])) <> "" then
				                    [result.trivento_unidadetrivento]
				
				            // Se não tiver, usa Origem Lead ID
				            else if Text.Contains(Text.Upper(Text.From([Origem Lead ID])), "ALTAMIRA") then "Altamira"
				            else if Text.Contains(Text.Upper(Text.From([Origem Lead ID])), "LORENA") then "Lorena"
				            else if Text.Contains(Text.Upper(Text.From([Origem Lead ID])), "ITABIRITO") then "Itabirito"
				            else if Text.Contains(Text.Upper(Text.From([Origem Lead ID])), "CANAA") then "Canaã"
				            else if Text.Contains(Text.Upper(Text.From([Origem Lead ID])), "CANAÃ") then "Canaã"
				            else [Unidade]
				
				        else [Unidade],
				    Replacer.ReplaceValue,
				    {"Unidade"}
				),
				
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Unidade Corrigida",{{"result.cad_campaigncontent", "UTM Content"}, {"result.cad_campaignmedium", "UTM Medium"}, {"result.cad_campaignname", "UTM Name"}, {"result.cad_campaignsource", "UTM Source"}, {"result.cad_campaignterm", "UTM Term"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"Numero Inscricao"}, Inscricoes, {"result.cad_numeroinscricao"}, "Inscricoes", JoinKind.LeftOuter),
				    #"Inscricoes Expandido1" = Table.ExpandTableColumn(#"Consultas Mescladas", "Inscricoes", {"Forma de Ingresso", "Curso ID", "Situação Inscrição", "Situação de Avaliação", "Unidade Inscrito", "Data Aprovação", "Situação Pagamento", "Data de Pagamento"}, {"Forma de Ingresso", "Curso ID", "Situação Inscrição", "Situação de Avaliação", "Unidade Inscrito", "Data Aprovação", "Situação Pagamento", "Data de Pagamento"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Inscricoes Expandido1","Canaa","Canaã",Replacer.ReplaceText,{"Unidade"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído",{{"Unidade", Text.Proper, type text}}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula",",","",Replacer.ReplaceText,{"Endereço"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",null,"Lead",Replacer.ReplaceValue,{"Situação Inscrição"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2","ADMINISTRAÇÃO","Administração",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","Análise de Desenvolvimento de Sistemas","Análise e Desenvolvimento de Sistemas",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","EDUCAÇÃO FÍSICA","Educação Física",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído5","Educação Fisica","Educação Física",Replacer.ReplaceText,{"Curso ID"}),
				    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído6","Odontoligia","Odontologia",Replacer.ReplaceText,{"Curso ID"}),
				    #"Curso Unidade Adicionado" = Table.AddColumn(#"Valor Substituído7", "Curso Unidade", each [Unidade Inscrito] & "-" & [Curso ID]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Curso Unidade Adicionado",{{"Curso Unidade", type text}}),
				    #"Valor Substituído8" = Table.ReplaceValue(#"Tipo Alterado"," -","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído9" = Table.ReplaceValue(#"Valor Substituído8","-","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído10" = Table.ReplaceValue(#"Valor Substituído9"," Faculdade Serra Dourada Altamira","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído11" = Table.ReplaceValue(#"Valor Substituído10"," Faculdade Serra Dourada Canaã","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído12" = Table.ReplaceValue(#"Valor Substituído11"," Faculdade Serra Dourada Lorena","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído13" = Table.ReplaceValue(#"Valor Substituído12"," Faculdade Alis","",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Valor Substituído14" = Table.ReplaceValue(#"Valor Substituído13","Concurso de Bolsas ","Concurso de Bolsas",Replacer.ReplaceText,{"Forma de Ingresso"}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Valor Substituído14", "Unidade.1", each if [Unidade Inscrito] = null or Text.Trim([Unidade Inscrito]) = "" then
				    [result.crmeduc_unidadeform]
				else
				    [Unidade Inscrito]),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Personalização Adicionada2",{{"Unidade", "Unidade Lead"}, {"Unidade.1", "Unidade"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Unidade", type text}})
				in
				    #"Tipo Alterado1"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

