table Atendimentos
	lineageTag: 48aff271-58b6-4af5-97f5-c49aed976afd

	column 'Canal de Origem'
		dataType: string
		lineageTag: 025e9b84-c27d-4c72-9339-ea9d2bc95b80
		summarizeBy: none
		sourceColumn: Canal de Origem

		annotation SummarizationSetBy = Automatic

	column 'Resultado do Contato'
		dataType: string
		lineageTag: 61d450a7-cf0c-459c-bfa0-eca20a67d820
		summarizeBy: none
		sourceColumn: Resultado do Contato

		annotation SummarizationSetBy = Automatic

	column 'Criado por'
		dataType: string
		lineageTag: 2700d898-82fb-4327-9d96-31e71f4a49c7
		summarizeBy: none
		sourceColumn: Criado por

		annotation SummarizationSetBy = Automatic

	column 'Data de Criação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0c6dbe58-0358-4c36-b15e-92de3feef206
		summarizeBy: none
		sourceColumn: Data de Criação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Modificado por'
		dataType: string
		lineageTag: 70f1aa29-be81-4d0f-a595-65ac8b4f3b32
		summarizeBy: none
		sourceColumn: Modificado por

		annotation SummarizationSetBy = Automatic

	column 'Data Modificação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bdb89b1-de53-4f61-885e-4fe7156fe1fa
		summarizeBy: none
		sourceColumn: Data Modificação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Id Lead'
		dataType: string
		lineageTag: 6a99cd27-ea33-435a-b720-dafbf5800acd
		summarizeBy: none
		sourceColumn: Id Lead

		annotation SummarizationSetBy = Automatic

	column Assunto
		dataType: string
		lineageTag: d440a88f-fce9-40d2-9ff5-dfaaf9b752c0
		summarizeBy: none
		sourceColumn: Assunto

		annotation SummarizationSetBy = Automatic

	column 'result.activityid'
		dataType: string
		lineageTag: 3e6b8d48-7111-481c-be0e-3932fd568351
		summarizeBy: none
		sourceColumn: result.activityid

		annotation SummarizationSetBy = Automatic

	column 'result.cad_atendente'
		dataType: string
		lineageTag: c178918b-6d2e-434a-b82f-655c84c53b48
		summarizeBy: none
		sourceColumn: result.cad_atendente

		annotation SummarizationSetBy = Automatic

	column 'Attribute:name.1'
		dataType: string
		lineageTag: 51512b94-5f76-4b7e-bdd8-09f349eb38ea
		summarizeBy: none
		sourceColumn: Attribute:name.1

		annotation SummarizationSetBy = Automatic

	column 'Retorno de Contato'
		dataType: string
		lineageTag: c06e0c90-32a4-4374-9264-13897b03cb0d
		summarizeBy: none
		sourceColumn: Retorno de Contato

		annotation SummarizationSetBy = Automatic

	column 'hora de Criação'
		dataType: string
		lineageTag: 509067db-c9a3-4b9c-be8c-9c802fdcfd4b
		summarizeBy: none
		sourceColumn: hora de Criação

		annotation SummarizationSetBy = Automatic

	column 'result.description'
		dataType: string
		lineageTag: a91362b7-e987-4975-a7e1-a7240ad53385
		summarizeBy: none
		sourceColumn: result.description

		annotation SummarizationSetBy = Automatic

	column 'Hora da Modificação'
		dataType: string
		lineageTag: 9e1733e6-0fca-46f5-81be-18809b5a723d
		summarizeBy: none
		sourceColumn: Hora da Modificação

		annotation SummarizationSetBy = Automatic

	column 'Nome do Lead'
		dataType: string
		lineageTag: 020bee75-eca3-41f7-8ade-3a4b2567c935
		summarizeBy: none
		sourceColumn: Nome do Lead

		annotation SummarizationSetBy = Automatic

	partition Atendimentos = m
		mode: import
		queryGroup: 'Consultas - Token'
		source =
				let
				    Token = #"Token de acesso"(),
				
				    url = "https://trivento.api.crmeducacional.com/api/LocalizacaoAvancada",
				
				    body =
				"<fetch version=""1.0"" output-format=""xml-platform"" mapping=""logical"" distinct=""true"">#(lf)  <entity name=""cad_atendimento"" all-attributes=""true"">#(lf)    <order attribute=""createdon"" descending=""true""/>#(lf)  </entity>#(lf)</fetch>",
				    GetPage = (Pagina as number) =>
				        let
				            Fonte =
				                Web.Contents(
				                    url,
				                    [
				                        Headers = [
				                            Authorization = "Bearer " & Token,
				                            #"Content-Type" = "application/xml",
				                            Pagina = Text.From(Pagina)
				                        ],
				                        Content = Text.ToBinary(body)
				                    ]
				                ),
				
				            XmlConvertido = Xml.Tables(Fonte),
				
				            Resultados =
				                try XmlConvertido{0}[result] otherwise null,
				
				            MoreRecords =
				                try XmlConvertido{0}[morerecords] otherwise "0"
				
				        in
				            [
				                Data = Resultados,
				                More = MoreRecords
				            ],
				    Paginas = List.Generate(
				            () => [Pg = 1, Resultado = GetPage(1)],
				            each [Resultado][Data] <> null,
				            each [
				                Pg = [Pg] + 1,
				                Resultado = GetPage([Pg])
				            ],
				            each [Resultado][Data]
				        ),
				    tabela_final = Table.Combine(
				    List.Transform(
				        Paginas,
				        each Table.PrefixColumns(_, "result")
				    )
				),
				    #"Canal Origem" = Table.ExpandTableColumn(tabela_final, "result.cad_canaldeorigem", {"Attribute:name"}, {"Canal de Origem"}),
				    #"result.cad_direcao Expandido" = Table.ExpandTableColumn(#"Canal Origem", "result.cad_direcao", {"Attribute:name"}, {"Attribute:name.1"}),
				    #"Resultado do Contato" = Table.ExpandTableColumn(#"result.cad_direcao Expandido", "result.cad_resultadosdocontato", {"Attribute:name"}, {"Resultado do Contato"}),
				    #"Retorno do Contato" = Table.ExpandTableColumn(#"Resultado do Contato", "result.cad_retornodecontato", {"Attribute:name"}, {"Retorno de Contato"}),
				    #"Criado por" = Table.ExpandTableColumn(#"Retorno do Contato", "result.createdby", {"Attribute:name"}, {"Criado por"}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Criado por","# ","",Replacer.ReplaceText,{"Criado por"}),
				    #"Data e hora de criação" = Table.ExpandTableColumn(#"Valor Substituído", "result.createdon", {"Attribute:date", "Attribute:time"}, {"Attribute:date", "Attribute:time"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Data e hora de criação",{{"Attribute:date", "Data de Criação"}, {"Attribute:time", "hora de Criação"}}),
				    #"Modificado por" = Table.ExpandTableColumn(#"Colunas Renomeadas", "result.modifiedby", {"Attribute:name"}, {"Modificado por"}),
				    #"Data e hora de Modificação" = Table.ExpandTableColumn(#"Modificado por", "result.modifiedon", {"Attribute:date", "Attribute:time"}, {"Data Modificação", "Hora da Modificação"}),
				    #"renomeado para assunto" = Table.RenameColumns(#"Data e hora de Modificação",{{"result.subject", "Assunto"}, {"result.cad_detalhesdocontato", "detalhes do contato"}}),
				    #"id e nome do lead" = Table.ExpandTableColumn(#"renomeado para assunto", "result.regardingobjectid", {"Element:Text", "Attribute:name"}, {"Id Lead", "Nome do Lead"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"id e nome do lead",{{"Data de Criação", type date}, {"Data Modificação", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

