/// Candidatos consolidados da API Zenvia Sales em janelas de até 31 dias, com dados do atendente.
table 'Candidatos Zenvia'
	lineageTag: 87316862-c365-4131-9550-58afa6e2b296

	column candidato_id
		dataType: string
		lineageTag: 7914bde9-ddc9-42ae-bb7d-281218e1bf1f
		sourceColumn: candidato_id

	column candidato_nome
		dataType: string
		lineageTag: c6385c62-58c4-4ee7-832c-68bf9e31ff59
		sourceColumn: candidato_nome

	column candidato_status
		dataType: string
		lineageTag: 705ce257-d929-4834-9f29-3edb27e5bdaa
		sourceColumn: candidato_status

	column candidato_criado_em
		dataType: dateTime
		lineageTag: 415602bb-4202-40de-b62b-621f8a4196fd
		sourceColumn: candidato_criado_em

	column candidato_telefones
		dataType: string
		lineageTag: 4b77e88e-23e9-4abc-8dbe-821b4b8c7550
		sourceColumn: candidato_telefones

	column candidato_emails
		dataType: string
		lineageTag: da680fae-8230-4217-ad66-80c704062412
		sourceColumn: candidato_emails

	column atendente_id
		dataType: string
		lineageTag: b3d0747e-ffc1-435c-a0cd-57c6482a8c8e
		sourceColumn: atendente_id

	column atendente_nome
		dataType: string
		lineageTag: 2afe8b5a-0107-4a56-9ae2-752c275dbff8
		sourceColumn: atendente_nome

	column atendente_email
		dataType: string
		lineageTag: 55cefcbd-7f0a-4729-9723-4c6d13e6916c
		sourceColumn: atendente_email

	column atendente_telefone
		dataType: string
		lineageTag: fb8dfbe8-5653-4873-b427-082ad5eced14
		sourceColumn: atendente_telefone

	partition 'Candidatos Zenvia' = m
		mode: import
		source =
				let
				    BaseUrl = "https://sales.zenvia.com",
				    DataInicio = DateTimeZone.FromText(ZenviaDataInicio),
				    DataFim = DateTimeZone.FromText(ZenviaDataFim),
				
				    LimitarFim = (Valor as datetimezone) as datetimezone =>
				        if Valor > DataFim then DataFim else Valor,
				
				    Periodos = List.Generate(
				        () => [
				            Inicio = DataInicio,
				            Fim = LimitarFim(DataInicio + #duration(31, 0, 0, 0))
				        ],
				        each [Inicio] < DataFim,
				        each [
				            Inicio = [Fim],
				            Fim = LimitarFim([Fim] + #duration(31, 0, 0, 0))
				        ],
				        each _
				    ),
				
				    BuscarPeriodo = (Periodo as record) as list =>
				        let
				            InicioTexto = DateTimeZone.ToText(
				                Periodo[Inicio],
				                "yyyy-MM-ddTHH:mm:ss.fffZ",
				                "en-US"
				            ),
				            FimTexto = DateTimeZone.ToText(
				                Periodo[Fim],
				                "yyyy-MM-ddTHH:mm:ss.fffZ",
				                "en-US"
				            ),
				            Resposta = Json.Document(
				                Web.Contents(
				                    BaseUrl,
				                    [
				                        RelativePath = "api/v1/prospects",
				                        Query = [
				                            createdAfter = InicioTexto,
				                            createdBefore = FimTexto
				                        ],
				                        Headers = [
				                            #"api-key" = ZenviaApiKey,
				                            Accept = "application/json"
				                        ],
				                        Timeout = #duration(0, 0, 2, 0)
				                    ]
				                )
				            ),
				            Candidatos = if Value.Is(Resposta, type list)
				                then Resposta
				                else error "A API da Zenvia retornou um formato diferente de lista."
				        in
				            Candidatos,
				
				    TodosCandidatos = List.Combine(
				        List.Transform(Periodos, each BuscarPeriodo(_))
				    ),
				
				    Texto = (Valor as any) as nullable text =>
				        if Valor = null then null else Text.From(Valor),
				
				    TextoLista = (Valor as any) as nullable text =>
				        if Value.Is(Valor, type list)
				        then Text.Combine(List.Transform(Valor, each Text.From(_)), ", ")
				        else Texto(Valor),
				
				    NomeCompleto = (PrimeiroNome as any, UltimoNome as any) as text =>
				        Text.Combine(
				            List.Select(
				                {Texto(PrimeiroNome), Texto(UltimoNome)},
				                each _ <> null and Text.Trim(_) <> ""
				            ),
				            " "
				        ),
				
				    NormalizarCandidato = (Candidato as record) as record =>
				        let
				            Agente = Record.FieldOrDefault(Candidato, "agent", null),
				            CampoAgente = (NomeCampo as text) as any =>
				                if Value.Is(Agente, type record)
				                then Record.FieldOrDefault(Agente, NomeCampo, null)
				                else null
				        in
				            [
				                candidato_id = Texto(Record.FieldOrDefault(Candidato, "id", null)),
				                candidato_nome = NomeCompleto(
				                    Record.FieldOrDefault(Candidato, "firstName", null),
				                    Record.FieldOrDefault(Candidato, "lastName", null)
				                ),
				                candidato_status = Texto(Record.FieldOrDefault(Candidato, "status", null)),
				                candidato_criado_em =
				                    try DateTime.From(
				                        DateTimeZone.FromText(
				                            Texto(Record.FieldOrDefault(Candidato, "created", null))
				                        )
				                    )
				                    otherwise null,
				                candidato_telefones = TextoLista(
				                    Record.FieldOrDefault(Candidato, "phones", null)
				                ),
				                candidato_emails = TextoLista(
				                    Record.FieldOrDefault(Candidato, "emails", null)
				                ),
				                atendente_id = Texto(CampoAgente("id")),
				                atendente_nome = NomeCompleto(
				                    CampoAgente("firstName"),
				                    CampoAgente("lastName")
				                ),
				                atendente_email = Texto(CampoAgente("email")),
				                atendente_telefone = Texto(CampoAgente("phone"))
				            ],
				
				    Registros = List.Transform(TodosCandidatos, each NormalizarCandidato(_)),
				
				    Tabela = Table.FromRecords(
				        Registros,
				        type table [
				            candidato_id = nullable text,
				            candidato_nome = nullable text,
				            candidato_status = nullable text,
				            candidato_criado_em = nullable datetime,
				            candidato_telefones = nullable text,
				            candidato_emails = nullable text,
				            atendente_id = nullable text,
				            atendente_nome = nullable text,
				            atendente_email = nullable text,
				            atendente_telefone = nullable text
				        ]
				    ),
				
				    SemDuplicatas = Table.Distinct(Tabela, {"candidato_id"})
				in
				    SemDuplicatas

