table conversas_zenvia
	lineageTag: 9a63601c-f527-4f9d-b76b-6ed1a331e02e

	column prospect_id
		dataType: string
		lineageTag: c04e2ca3-5d85-4cd4-a01a-405a6866a258
		summarizeBy: none
		sourceColumn: prospect_id

		annotation SummarizationSetBy = Automatic

	column inicio
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e92be47-455b-440c-a5fd-9f24471e015a
		summarizeBy: none
		sourceColumn: inicio

		variation Variation
			isDefault
			relationship: 47a0b05f-fd5b-47cd-868f-d141c5f543eb
			defaultHierarchy: LocalDateTable_30b3a768-a3ec-464d-a1e3-f50bd35b53f1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fim
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0935507-3c73-4be9-a9bd-90bf353558ed
		summarizeBy: none
		sourceColumn: fim

		variation Variation
			isDefault
			relationship: 6e6db020-193a-41ab-82b3-18b3b3a829b7
			defaultHierarchy: LocalDateTable_acfeed69-c1e8-436e-9b68-8835cc97e274.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_mensagens
		dataType: int64
		formatString: 0
		lineageTag: 578d1da9-1e26-4b50-a9d1-3596d2caddff
		summarizeBy: sum
		sourceColumn: total_mensagens

		annotation SummarizationSetBy = Automatic

	column agente
		dataType: string
		lineageTag: 21e2754f-a732-4002-95ff-5d69cc6785cb
		summarizeBy: none
		sourceColumn: agente

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: 3cccdfe4-a04d-4d59-af4a-25fd2d87131a
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column mensagens
		dataType: string
		lineageTag: fc3880cc-6cf6-492f-8340-7cdfa1d9b3d0
		summarizeBy: none
		sourceColumn: mensagens

		annotation SummarizationSetBy = Automatic

	column assunto
		dataType: string
		lineageTag: 13129f23-28c1-44c3-8e76-f27dd6c08a62
		summarizeBy: none
		sourceColumn: assunto

		annotation SummarizationSetBy = Automatic

	column motivo_principal
		dataType: string
		lineageTag: 9ac1238d-c2ee-48da-a4b1-d8545cb03a2f
		summarizeBy: none
		sourceColumn: motivo_principal

		annotation SummarizationSetBy = Automatic

	column intencao_matricula
		dataType: string
		lineageTag: 6f298e4e-b844-4503-a58c-9b4426d1a616
		summarizeBy: none
		sourceColumn: intencao_matricula

		annotation SummarizationSetBy = Automatic

	column urgencia
		dataType: string
		lineageTag: eeb5e1fb-1a5b-492d-b90a-8e38f1bff28f
		summarizeBy: none
		sourceColumn: urgencia

		annotation SummarizationSetBy = Automatic

	column sentimento
		dataType: string
		lineageTag: 779eea51-0925-4059-b3d2-c12e46fbe91c
		summarizeBy: none
		sourceColumn: sentimento

		annotation SummarizationSetBy = Automatic

	column risco_perda
		dataType: string
		lineageTag: 8be43226-6aef-42a8-87ef-371f7f2e20b1
		summarizeBy: none
		sourceColumn: risco_perda

		annotation SummarizationSetBy = Automatic

	column primeiro_nome
		dataType: string
		lineageTag: d8b0068f-916f-4bb3-b9a0-0469d904c503
		summarizeBy: none
		sourceColumn: primeiro_nome

		annotation SummarizationSetBy = Automatic

	column sobrenome
		dataType: string
		lineageTag: 61ff73d4-927a-4501-8a8a-050d5a044743
		summarizeBy: none
		sourceColumn: sobrenome

		annotation SummarizationSetBy = Automatic

	column telefone
		dataType: int64
		formatString: 0
		lineageTag: c2528abf-82cb-4547-b73f-01abb46df671
		summarizeBy: sum
		sourceColumn: telefone

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: f8cbb95b-031e-4afe-b003-cd24881e8a92
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column Telefone_normalizado
		dataType: int64
		formatString: 0
		lineageTag: 15b658e2-c6ef-48f4-90b3-1cfb4af6b405
		summarizeBy: sum
		sourceColumn: Telefone_normalizado

		annotation SummarizationSetBy = Automatic

	column 'Celular Comparar Legado'
		dataType: int64
		formatString: 0
		lineageTag: 6c40da34-6e16-4a34-a9a5-5e1c7c6b042b
		summarizeBy: sum
		sourceColumn: Celular Comparar Legado

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 2080426b-49ac-45a0-b1e9-9ff8b3545768
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Data Criacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1b3ab0ec-fc31-4850-a758-bb18bb3f4778
		summarizeBy: none
		sourceColumn: Data Criacao

		variation Variation
			isDefault
			relationship: 37d43a85-7ab6-4f54-ac9f-91ec92c5332b
			defaultHierarchy: LocalDateTable_9d4c102e-a278-481e-9f00-f2f48493bca0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Pagamento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 51e39a86-1345-41f1-9334-caeb3bc9815c
		summarizeBy: none
		sourceColumn: Data de Pagamento

		variation Variation
			isDefault
			relationship: 90ce093d-bf2e-4be2-9cbe-a26c904fa292
			defaultHierarchy: LocalDateTable_86fd4a56-b2f5-47fb-a3fe-fcd23f5925c9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Situação Inscrição'
		dataType: string
		lineageTag: d7772ed2-03f9-4a62-ba81-0cec570289ed
		summarizeBy: none
		sourceColumn: Situação Inscrição

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: d2581984-f439-4103-aee5-09bb4be9bb6e
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column Curso_1
		dataType: string
		lineageTag: d7b9a516-8137-48b5-bd3f-a6d89dfb6e91
		summarizeBy: none
		sourceColumn: Curso_1

		annotation SummarizationSetBy = Automatic

	partition conversas_zenvia = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Files("https://grupoeducacionalsantoant.sharepoint.com/sites/TriventoEducaco", [ApiVersion = 15]),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Name] = "conversas_zenvia.xlsx")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Arquivos Ocultos Filtrados2" = Table.SelectRows(#"Invocar Função Personalizada1", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada2" = Table.AddColumn(#"Arquivos Ocultos Filtrados2", "Transformar Arquivo (2)", each #"Transformar Arquivo (2)"([Content])),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Invocar Função Personalizada2", {"Transformar Arquivo (2)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (2)", Table.ColumnNames(#"Transformar Arquivo (2)"(#"Arquivo de Amostra (2)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"prospect_id", type text}, {"inicio", type date}, {"fim", type date}, {"total_mensagens", Int64.Type}, {"agente", type text}, {"canal", type text}, {"mensagens", type text}, {"assunto", type text}, {"motivo_principal", type text}, {"intencao_matricula", type text}, {"urgencia", type text}, {"sentimento", type text}, {"risco_perda", type text}, {"primeiro_nome", type any}, {"sobrenome", type any}, {"email", type any}, {"telefone", Int64.Type}, {"Telefone_normalizado", Int64.Type}, {"Celular Comparar Legado", Int64.Type}, {"Unidade", type text}, {"Data Criacao", type date}, {"Data de Pagamento", type date}, {"Situação Inscrição", type text}, {"Curso", type text}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each ([agente] <> null and [agente] <> "Beatriz Oliveira" and [agente] <> "Camila Guimarães Santos" and [agente] <> "Caroline Mahé" and [agente] <> "Dev Trivento" and [agente] <> "Laiane Silva" and [agente] <> "Leonardo Alves" and [agente] <> "MARCO TULIO" and [agente] <> "Natália Franco" and [agente] <> "Rafaela Fernandes" and [agente] <> "Wallace Guilherme"))
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

