table dAtendentes
	lineageTag: a20427fb-c742-431f-82d9-cb91d255774c

	column 'Criado por'
		dataType: string
		lineageTag: 16b22626-fa9a-45ed-bce7-04ce7b49d292
		summarizeBy: none
		sourceColumn: Criado por

		annotation SummarizationSetBy = Automatic

	column Equipe =
			
			SWITCH(
			    dAtendentes[Criado por],
			    "Maria Fernanda Luiz Monteiro", "Unidade Lorena",
			    "Maria Eduarda Freire", "Unidade Lorena",
			    "Ana Carolina Guimarães", "Célula",
			    "Thiago Oliveira da Cruz", "Unidade Altamira",
			    "Giovanna Eduarda Do Carmo Braga", "Unidade Itabirito",
			    "Hailton Alves Júnior", "Célula",
			    "Maria Rafaela da Rocha Tavares", "Unidade Lorena",
			    "Daniel Faria Santos", "Célula",
			    "Thalia Gabriela de Araújo Silva", "Unidade Lorena",
			    "Lorena Viana Gonçalves Pereira", "Célula",
			    "Karolaine de Oliveira Alves Souza", "Célula",
			    "Adauri Marques Delfino Junior", "Célula",
			    "Geovana Souza da Silva", "Unidade Altamira",
			    "Agnata Pamela Silva Souza", "Unidade Lorena",
			    "Karen Flávia", "Unidade Canaã",
			    "Matheus Duarte", "Sem Equipe",
			    "Caroline Mahe", "Sem Equipe",
			    "Camila Guimarães Santos", "Sem Equipe",
			    "Fernanda Santos", "Sem Equipe",
			    "Thalyta Costa", "Sem Equipe",
			    "Breno Assis Ferreira",  "Célula",
			    "Flavio Henrique de Oliveira", "Sem Equipe",
			    "Sem Equipe"
			)
		lineageTag: 30a26d64-c5b8-42f7-bdec-0880781837cc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Proprietário lead'
		dataType: string
		lineageTag: 85370991-4102-4bff-b26e-c41aee647a19
		summarizeBy: none
		sourceColumn: Proprietário lead

		annotation SummarizationSetBy = Automatic

	column Consultor =
			
			SWITCH(
			    dAtendentes[Criado por],
			    "Gabriel Matos", "Gabriel",
			    "Maria Eduarda Freire", "Duda",
			    "Maria Rafaela da Rocha Tavares", "Maria Rafaela",
			    "Adauri Marques Delfino Junior", "Adauri",
			    "Karen Flávia", "Flávia",
			    "Daniel Faria Santos", "Daniel",
			    "Geovana Souza da Silva", "Geovana",
			    "Agnata Pamela Silva Souza", "Agnata",
			    "Giovanna Eduarda Do Carmo Braga", "Giovanna Braga",
			    "Hailton Alves Júnior", "Hailton",
			    "Karolaine de Oliveira Alves Souza", "Karolaine",
			    "Thiago Oliveira da Cruz", "Thiago",
			    "Maria Fernanda Luiz Monteiro", "Maria Fernanda",
			    "Ana Carolina Guimarães", "Ana Carolina",
			    "Lorena Viana Gonçalves Pereira", "Lorena",
			    "Thalia Gabriela de Araújo Silva", "Thalia",
			    "Camila Guimarães Santos", "Camila",
			    "Breno Assis Ferreira", "Breno"
			)
		lineageTag: 36810220-415d-4140-9138-a43d74515cf4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dAtendentes = m
		mode: import
		queryGroup: 'Consultas - Token'
		source =
				let
				    Fonte = Atendimentos,
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte,{"Criado por"}),
				    fnNormalizaNome = (valor as nullable text) as nullable text =>
				        let
				            TextoBase = if valor = null then null else Text.Lower(Text.Trim(Text.Clean(Text.Replace(valor, Character.FromNumber(160), " ")))),
				            TextoSemAcentos = if TextoBase = null then null else List.Accumulate(
				                {
				                    {"á", "a"}, {"à", "a"}, {"â", "a"}, {"ã", "a"}, {"ä", "a"},
				                    {"é", "e"}, {"ê", "e"}, {"ë", "e"},
				                    {"í", "i"}, {"ï", "i"},
				                    {"ó", "o"}, {"ô", "o"}, {"õ", "o"}, {"ö", "o"},
				                    {"ú", "u"}, {"ü", "u"},
				                    {"ç", "c"}
				                },
				                TextoBase,
				                (state, current) => Text.Replace(state, current{0}, current{1})
				            ),
				            TextoSemPontuacao = if TextoSemAcentos = null then null else List.Accumulate(
				                {".", ",", "-", "(", ")", "/", "'", ":"},
				                TextoSemAcentos,
				                (state, current) => Text.Replace(state, current, "")
				            ),
				            Tokens = if TextoSemPontuacao = null then null else List.Select(Text.SplitAny(TextoSemPontuacao, " "), each _ <> ""),
				            Resultado = if Tokens = null then null else Text.Combine(Tokens, " ")
				        in
				            Resultado,
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Chave Criado por" = Table.AddColumn(#"Duplicatas Removidas", "Chave Normalizada", each fnNormalizaNome([Criado por]), type text),
				    #"Proprietários Distintos" = Table.Distinct(
				        Table.AddColumn(
				            Table.SelectColumns(#"2026-2", {"Proprietário Lead"}),
				            "Chave Normalizada",
				            each fnNormalizaNome([Proprietário Lead]),
				            type text
				        ),
				        {"Chave Normalizada"}
				    ),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Chave Criado por", {"Chave Normalizada"}, #"Proprietários Distintos", {"Chave Normalizada"}, "2026-2", JoinKind.LeftOuter),
				    #"Proprietário lead Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "2026-2", {"Proprietário Lead"}, {"Proprietário lead"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Proprietário lead Expandido",{"Chave Normalizada"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

