table dCurso
	lineageTag: 8785b4b3-24ce-43aa-a4cf-56ecbcf47f63

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 10886c5e-8591-4a11-a1ad-6686cf08ae16
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Curso ID'
		dataType: string
		lineageTag: 5cd337d8-bd13-4ec2-9758-1a33891f82bd
		summarizeBy: none
		sourceColumn: Curso ID

		annotation SummarizationSetBy = Automatic

	column 'Unidade Inscrito'
		dataType: string
		lineageTag: e78bda5f-0be4-42c3-bccd-015308dfa6cd
		summarizeBy: none
		sourceColumn: Unidade Inscrito

		annotation SummarizationSetBy = Automatic

	column 'Curso Unidade'
		dataType: string
		lineageTag: 17aa65f6-2f1c-416e-a8f5-2a4f8ed822cd
		summarizeBy: none
		sourceColumn: Curso Unidade

		annotation SummarizationSetBy = Automatic

	column Meta
		dataType: int64
		formatString: 0
		lineageTag: 078a68d1-0aa8-4600-bb4a-3b8296b5433b
		summarizeBy: sum
		sourceColumn: Meta

		annotation SummarizationSetBy = Automatic

	partition dCurso = m
		mode: import
		queryGroup: 'Consultas - Token'
		source =
				let
				    Fonte = #"2026-2",
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte,{"Curso ID", "Unidade Inscrito", "Curso Unidade"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Classificadas" = Table.Sort(#"Linhas em Branco Removidas",{{"Curso ID", Order.Ascending}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Classificadas", {"Curso Unidade"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Duplicatas Removidas", {"Curso Unidade"}, #"Metas Curso", {"Unidade Curso"}, "Metas Curso", JoinKind.LeftOuter),
				    #"Metas Curso Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Metas Curso", {"Meta"}, {"Meta"}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Metas Curso Expandido", "Índice", 1, 1, Int64.Type),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Índice Adicionado",{"Índice", "Curso ID", "Unidade Inscrito", "Curso Unidade", "Meta"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Reordenadas",{{"Índice", "ID"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

