table dUnidade
	lineageTag: f42ed6c3-0d2f-4805-900d-f3f333549678

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b1f4c575-3e0d-453b-8cdf-093762a163b2
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: c2c15910-8ced-4b54-a49f-4e7bcc092024
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	partition dUnidade = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows({
				        {1, "Altamira"},
				        {2, "Itabirito"},
				        {3, "Lorena"},
				        {4, "Canaã"}
				    }, {"ID", "Unidade"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ID", Int64.Type}, {"Unidade", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

