table Leads
	lineageTag: 5d5c91c8-075a-48fa-9e31-f3a2365489f1

	column 'result.address1_addressid'
		dataType: string
		lineageTag: 056782c9-e3c9-4dc8-9431-f4e708e31b7a
		summarizeBy: none
		sourceColumn: result.address1_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.address2_addressid'
		dataType: string
		lineageTag: 147afdb5-804b-4be2-ab55-59e4e97b88cc
		summarizeBy: none
		sourceColumn: result.address2_addressid

		annotation SummarizationSetBy = Automatic

	column 'result.cad_browser'
		dataType: string
		lineageTag: 7dc8342e-f9cc-469d-89bb-236fa890906b
		summarizeBy: none
		sourceColumn: result.cad_browser

		annotation SummarizationSetBy = Automatic

	column 'result.cad_campaignmedium'
		dataType: string
		lineageTag: 52ae9e2b-495f-4c97-8f90-3c9cc2ffd36c
		summarizeBy: none
		sourceColumn: result.cad_campaignmedium

		annotation SummarizationSetBy = Automatic

	column 'result.cad_campaignname'
		dataType: string
		lineageTag: 641e48df-1570-4bab-a780-d13ed2763224
		summarizeBy: none
		sourceColumn: result.cad_campaignname

		annotation SummarizationSetBy = Automatic

	column 'result.cad_campaignsource'
		dataType: string
		lineageTag: e3f2bf25-4efd-4faa-993f-0a9e2e38fb38
		summarizeBy: none
		sourceColumn: result.cad_campaignsource

		annotation SummarizationSetBy = Automatic

	column 'result.cad_campaignterm'
		dataType: string
		lineageTag: 8e5e3e58-eced-42c1-b8d1-3885f81cacda
		summarizeBy: none
		sourceColumn: result.cad_campaignterm

		annotation SummarizationSetBy = Automatic

	column 'Concurso Atual'
		dataType: string
		lineageTag: c905ff24-f16b-4c5a-b873-38dc9cdd901e
		summarizeBy: none
		sourceColumn: Concurso Atual

		annotation SummarizationSetBy = Automatic

	column 'Concurso Origem'
		dataType: string
		lineageTag: f5db1b56-d9d0-415c-a79d-98d5314620c4
		summarizeBy: none
		sourceColumn: Concurso Origem

		annotation SummarizationSetBy = Automatic

	column 'Data Aceite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 138d26c8-0c9e-47ea-a566-d220e40c19b2
		summarizeBy: none
		sourceColumn: Data Aceite

		variation Variation
			isDefault
			relationship: 5418f71d-907f-4786-a1f8-1e58fcecb5ea
			defaultHierarchy: LocalDateTable_13d55816-b77b-4b20-92a9-0ed12f17be0a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data alteração'
		dataType: dateTime
		formatString: General Date
		lineageTag: 840f1c96-1a1b-4299-b938-edec8f3e6ad1
		summarizeBy: none
		sourceColumn: Data alteração

		variation Variation
			isDefault
			relationship: b08de8a4-88dd-498a-9406-b3c5bae040f2
			defaultHierarchy: LocalDateTable_6209402d-885f-444f-b7f6-b9e38b768c04.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Numero Inscricao'
		dataType: string
		lineageTag: 9f613a32-2145-4c3f-a3e2-9c4a401734d7
		summarizeBy: none
		sourceColumn: Numero Inscricao

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: ef13b39c-2da7-4adc-a584-d4d27ac08798
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column 'Situacao Funil'
		dataType: string
		lineageTag: 678fe220-821a-48b8-ae89-caa1908084a4
		summarizeBy: none
		sourceColumn: Situacao Funil

		annotation SummarizationSetBy = Automatic

	column 'Data Criacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0cca0079-4c23-4e30-8b68-5820ea0a8318
		summarizeBy: none
		sourceColumn: Data Criacao

		variation Variation
			isDefault
			relationship: 00d93253-daf3-4df9-888b-a6d1f285003d
			defaultHierarchy: LocalDateTable_87e26fc0-fd37-4960-be28-b682fd6fb781.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unidade
		dataType: string
		lineageTag: 42ee26cd-f1cc-4b97-90b8-6aafd14bc83b
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: eb8a6551-a79a-40bf-8ac0-1f0f58ee015e
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: d5247393-5997-4cd2-877e-963cb5d0cde8
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 437f845b-1194-41b0-bfad-de6673ae9425
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column Sobrenome
		dataType: string
		lineageTag: 43e8e468-8587-432e-a0a4-33d130579c38
		summarizeBy: none
		sourceColumn: Sobrenome

		annotation SummarizationSetBy = Automatic

	column 'ID Lead'
		dataType: string
		lineageTag: 5bace0a8-a64c-4fdf-b2a8-30bad149c1fb
		summarizeBy: none
		sourceColumn: ID Lead

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead'
		dataType: string
		lineageTag: 44bbc821-4c30-4ebd-9331-e9cf673b685e
		summarizeBy: none
		sourceColumn: Origem Lead

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: string
		lineageTag: bb2a76c4-a263-4a12-a972-79d472f88e5f
		summarizeBy: none
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column 'Celular 2'
		dataType: string
		lineageTag: bcd4e1fd-ad20-425d-8ccd-647d7f1b7fb9
		summarizeBy: none
		sourceColumn: Celular 2

		annotation SummarizationSetBy = Automatic

	column 'Linha de Negócio'
		dataType: string
		lineageTag: ea3f4dc2-55ac-46ff-88b6-4202effa3d50
		summarizeBy: none
		sourceColumn: Linha de Negócio

		annotation SummarizationSetBy = Automatic

	column 'Origem Lead ID'
		dataType: string
		lineageTag: 99306296-b17d-4ed4-9ab6-7c1e6362cc5e
		summarizeBy: none
		sourceColumn: Origem Lead ID

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: 9952ac56-2a91-4197-9224-b25073052e01
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column 'result.crmeduc_unidadeform'
		dataType: string
		lineageTag: e6aa74b0-937a-47f7-abdb-9ae2741dcaa8
		summarizeBy: none
		sourceColumn: result.crmeduc_unidadeform

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 911a8e48-6943-4f96-b039-5e5f651fda25
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Endereço
		dataType: string
		lineageTag: 94d552fa-54c7-4cf7-9937-95716b7f195f
		summarizeBy: none
		sourceColumn: Endereço

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: c48cc08c-da91-4b31-ba59-943a74a4bcb8
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: 3991bf83-3cf3-451e-9282-eedbab88c003
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Rua
		dataType: string
		lineageTag: c49d630c-9f52-4c36-999b-5b4855983cef
		summarizeBy: none
		sourceColumn: Rua

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 1e1e4c79-da7d-4e46-b8ef-c2856fa1a7de
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: a2587d15-e610-4409-85be-7825406949ac
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: 2153ad74-e443-4d7a-b0f9-2463d2046f42
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 4be085d3-168b-464a-a8b1-12b9ac8620b7
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: string
		lineageTag: 24c7a0dc-4c23-42f8-871c-3268a2ea53f5
		summarizeBy: none
		sourceColumn: Data Nascimento

		annotation SummarizationSetBy = Automatic

	column 'Proprietário Lead'
		dataType: string
		lineageTag: bb2a85b0-822f-4c88-a864-7117480db9db
		summarizeBy: none
		sourceColumn: Proprietário Lead

		annotation SummarizationSetBy = Automatic

	column 'Tabulação Detalhe'
		dataType: string
		lineageTag: cacbfc2f-3e7e-41ed-9a94-5e75ceb6d1bd
		summarizeBy: none
		sourceColumn: Tabulação Detalhe

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: string
		lineageTag: 4a9b7860-c2b6-4808-84b5-8f8cc7b2c9b5
		summarizeBy: none
		sourceColumn: Idade

		annotation SummarizationSetBy = Automatic

	column Tabulação
		dataType: string
		lineageTag: f7d8b464-ee53-4d01-a4fc-1e52f883c4cd
		summarizeBy: none
		sourceColumn: Tabulação

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 9ca6d855-5ad4-4a08-b9ea-bfa696976ac1
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column RG
		dataType: string
		lineageTag: e59057b8-cdaa-4138-afe7-7a2fd860571b
		summarizeBy: none
		sourceColumn: RG

		annotation SummarizationSetBy = Automatic

	column 'result.cad_campaigncontent'
		dataType: string
		lineageTag: 173e88f7-9aa5-49cc-a32c-93bb04930e49
		summarizeBy: none
		sourceColumn: result.cad_campaigncontent

		annotation SummarizationSetBy = Automatic

	column Attribute:name
		dataType: string
		lineageTag: b939c1cd-0808-4ab5-a5ce-18d38927842d
		summarizeBy: none
		sourceColumn: Attribute:name

		annotation SummarizationSetBy = Automatic

	column 'Orgao Expedidor'
		dataType: string
		lineageTag: 1dd0b8ee-9296-491b-b521-433e8243ed73
		summarizeBy: none
		sourceColumn: Orgao Expedidor

		annotation SummarizationSetBy = Automatic

	column Cor
		dataType: string
		lineageTag: 3cac9209-cf5f-4b07-828f-57c199f81eb2
		summarizeBy: none
		sourceColumn: Cor

		annotation SummarizationSetBy = Automatic

	column 'Tabulação já foi realizada?'
		dataType: string
		lineageTag: 99a8c820-f52c-4e37-b572-94cca605e26a
		summarizeBy: none
		sourceColumn: Tabulação já foi realizada?

		annotation SummarizationSetBy = Automatic

	column 'Última Tabulação'
		dataType: string
		lineageTag: 1fd570f5-201a-43a9-b137-48a9fc24c578
		summarizeBy: none
		sourceColumn: Última Tabulação

		annotation SummarizationSetBy = Automatic

	partition Leads = m
		mode: import
		queryGroup: 'Consultas - Token'
		source =
				let
				    Token = #"Token de acesso"(),
				    url = "https://trivento.api.crmeducacional.com/api/LocalizacaoAvancada",
				
				body =
				"<fetch version=""1.0"" output-format=""xml-platform"" mapping=""logical"">#(lf)#(lf)  <entity name=""lead"">#(lf)#(lf)    <attribute name=""trivento_tabulacaojafoirealizada""/>#(lf)#(lf) <attribute name=""crmeduc_ultimatabulacao""/>#(lf)#(lf)   <attribute name=""fullname""/>#(lf)#(lf)    <attribute name=""firstname""/>#(lf)#(lf)    <attribute name=""lastname""/>#(lf)#(lf)    <attribute name=""emailaddress1""/>#(lf)#(lf)    <attribute name=""mobilephone""/>#(lf)#(lf)    <attribute name=""telephone1""/>#(lf)#(lf)    <attribute name=""leadid""/>#(lf)#(lf)    <attribute name=""createdon""/>#(lf)#(lf)    <attribute name=""address1_city""/>#(lf)#(lf)    <attribute name=""address1_composite""/>#(lf)#(lf)    <attribute name=""address1_country""/>#(lf)#(lf)    <attribute name=""address1_county""/>#(lf)#(lf)    <attribute name=""address1_line1""/>#(lf)#(lf)    <attribute name=""address1_line2""/>#(lf)#(lf)    <attribute name=""address1_line3""/>#(lf)#(lf)    <attribute name=""address1_postalcode""/>#(lf)#(lf)    <attribute name=""address1_stateorprovince""/>#(lf)#(lf)    <attribute name=""cad_nacionalidade""/>#(lf)#(lf)    <attribute name=""cad_orgaoexpedidor""/>#(lf)#(lf)    <attribute name=""cad_rg""/>#(lf)#(lf)    <attribute name=""crmeduc_unidadeform""/>#(lf)#(lf)    <attribute name=""crmeduc_detalhamentotabulacao""/>#(lf)#(lf)    <attribute name=""crmeduc_idade""/>#(lf)#(lf)    <attribute name=""cad_dataaceitelgpd""/>#(lf)#(lf)    <attribute name=""cad_dataalteracaocadastrooferta""/>#(lf)#(lf)    <attribute name=""cad_concursoatual""/>#(lf)#(lf)    <attribute name=""cad_concursodeorigem""/>#(lf)#(lf)    <attribute name=""cad_datanascimento""/>#(lf)#(lf)    <attribute name=""cad_inscricaoatual""/>#(lf)#(lf)    <attribute name=""cad_ofertaatual""/>#(lf)#(lf)    <attribute name=""cad_situacaofunil""/>#(lf)#(lf)    <attribute name=""cad_corraca""/>#(lf)#(lf)    <attribute name=""cad_origemleadid""/>#(lf)#(lf)    <attribute name=""cad_proprietariopro""/>#(lf)#(lf)    <attribute name=""crmeduc_canal""/>#(lf)#(lf)    <attribute name=""crmeduc_unidade""/>#(lf)#(lf)    <attribute name=""crmeduc_tabulacaodolead""/>#(lf)#(lf)    <attribute name=""leadsourcecode""/>#(lf)#(lf)    <attribute name=""new_sexo""/>#(lf)#(lf)    <attribute name=""trivento_linhadenegociostrivento""/>#(lf)#(lf)#(lf)    <attribute name=""cad_estadocivil""/>#(lf)#(lf)#(lf)    <attribute name=""cad_campaigncontent""/>#(lf)#(cr)#(lf)#(lf)    <attribute name=""cad_campaignmedium""/>#(lf)#(cr)#(lf)#(lf)    <attribute name=""cad_campaignname""/>#(lf)#(cr)#(lf)#(lf)    <attribute name=""cad_campaignsource""/>#(lf)#(cr)#(lf)#(lf)    <attribute name=""cad_campaignterm""/>#(lf)    #(cr)#(lf)  <attribute name=""address1_addressid""/>#(lf)#(cr)#(lf)#(lf)    <attribute name=""cad_browser""/>#(lf)    <attribute name=""address2_addressid""/>#(lf)#(cr)#(lf)#(cr)#(lf)#(cr)#(lf)<order attribute=""createdon"" descending=""true""/>#(lf)#(lf)  </entity>#(lf)#(lf)</fetch>",
				
				
				    // FUNÇÃO QUE BUSCA UMA PÁGINA
				    GetPage = (Pagina as number) =>
				        let
				            Fonte =
				                Web.Contents(
				                    url,
				                    [
				                        Headers = [
				                            Authorization = "Bearer " & Token,
				                            #"Content-Type" = "application/xml",
				                            Pagina = Text.From(Pagina)
				                        ],
				                        Content = Text.ToBinary(body)
				                    ]
				                ),
				
				            XmlConvertido = Xml.Tables(Fonte),
				
				            Resultados =
				                try XmlConvertido{0}[result] otherwise null,
				
				            MoreRecords =
				                try XmlConvertido{0}[morerecords] otherwise "0"
				
				        in
				            [
				                Data = Resultados,
				                More = MoreRecords
				            ],
				
				    // LOOP AUTOMÁTICO
				    Paginas =
				        List.Generate(
				            () => [Pg = 1, Resultado = GetPage(1)],
				            each [Resultado][Data] <> null,
				            each [
				                Pg = [Pg] + 1,
				                Resultado = GetPage([Pg])
				            ],
				            each [Resultado][Data]
				        ),
				
				    // JUNTA TODAS AS PÁGINAS
				    TabelaFinal = Table.Combine(
				    List.Transform(
				        Paginas,
				        each Table.PrefixColumns(_, "result")
				    )
				),
				    #"result.trivento_tabulacaojafoirealizada Expandido" = Table.ExpandTableColumn(TabelaFinal, "result.trivento_tabulacaojafoirealizada", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas19" = Table.RenameColumns(#"result.trivento_tabulacaojafoirealizada Expandido",{{"Attribute:name", "Tabulação já foi realizada?"}}),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Colunas Renomeadas19",{{"Tabulação já foi realizada?", type text}}),
				    #"Colunas Renomeadas20" = Table.RenameColumns(#"Tipo Alterado5",{{"result.crmeduc_ultimatabulacao", "Última Tabulação"}}),
				    #"result.crmeduc_canal Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas20", "result.crmeduc_canal", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas18" = Table.RenameColumns(#"result.crmeduc_canal Expandido",{{"Attribute:name", "Canal"}}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas18",{{"Canal", type text}}),
				    #"result.cad_concursoatual Expandido" = Table.ExpandTableColumn(#"Tipo Alterado4", "result.cad_concursoatual", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"result.cad_concursoatual Expandido",{{"Attribute:name", "Concurso Atual"}}),
				    #"result.cad_concursodeorigem Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas", "result.cad_concursodeorigem", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"result.cad_concursodeorigem Expandido",{{"Attribute:name", "Concurso Origem"}}),
				    #"result.cad_datanascimento Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas1", "result.cad_datanascimento", {"Attribute:date"}, {"Attribute:date"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"result.cad_datanascimento Expandido",{{"Attribute:date", "Data Nascimento"}}),
				    #"result.cad_inscricaoatual Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas2", "result.cad_inscricaoatual", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"result.cad_inscricaoatual Expandido",{{"Attribute:name", "Numero Inscricao"}}),
				    #"result.cad_ofertaatual Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas3", "result.cad_ofertaatual", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"result.cad_ofertaatual Expandido",{{"Attribute:name", "Curso"}}),
				    #"result.cad_situacaofunil Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas4", "result.cad_situacaofunil", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas5" = Table.RenameColumns(#"result.cad_situacaofunil Expandido",{{"Attribute:name", "Situacao Funil"}}),
				    #"result.createdon Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas5", "result.createdon", {"Attribute:date"}, {"Attribute:date"}),
				    #"Colunas Renomeadas6" = Table.RenameColumns(#"result.createdon Expandido",{{"Attribute:date", "Data Criacao"}}),
				    #"result.crmeduc_idade Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas6", "result.crmeduc_idade", {"Element:Text"}, {"Element:Text"}),
				    #"Colunas Renomeadas7" = Table.RenameColumns(#"result.crmeduc_idade Expandido",{{"Element:Text", "Idade"}, {"result.emailaddress1", "email"}, {"result.firstname", "Nome"}, {"result.fullname", "Nome Completo"}, {"result.lastname", "Sobrenome"}, {"result.leadid", "ID Lead"}}),
				    #"result.leadsourcecode Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas7", "result.leadsourcecode", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas8" = Table.RenameColumns(#"result.leadsourcecode Expandido",{{"Attribute:name", "Origem Lead"}, {"result.mobilephone", "Celular"}}),
				    #"result.new_sexo Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas8", "result.new_sexo", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas9" = Table.RenameColumns(#"result.new_sexo Expandido",{{"Attribute:name", "Sexo"}, {"result.telephone1", "Celular 2"}}),
				    #"result.trivento_linhadenegociostrivento Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas9", "result.trivento_linhadenegociostrivento", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas10" = Table.RenameColumns(#"result.trivento_linhadenegociostrivento Expandido",{{"Attribute:name", "Linha de Negócio"}, {"result.address1_city", "Cidade"}, {"result.address1_composite", "Endereço"}, {"result.address1_country", "Pais"}, {"result.address1_county", "Bairro"}, {"result.address1_line1", "Rua"}, {"result.address1_line2", "Número"}, {"result.address1_postalcode", "CEP"}, {"result.address1_stateorprovince", "UF"}, {"result.cad_nacionalidade", "Nacionalidade"}}),
				    #"result.cad_corraca Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas10", "result.cad_corraca", {"Attribute:name"}, {"Attribute:name"}),
				    #"Colunas Renomeadas11" = Table.RenameColumns(#"result.cad_corraca Expandido",{{"Attribute:name", "Cor"}, {"result.cad_orgaoexpedidor", "Orgao Expedidor"}, {"result.cad_rg", "RG"}, {"result.address1_line3", "Complemento"}}),
				    #"result.cad_estadocivil Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas11", "result.cad_estadocivil", {"Attribute:name"}, {"Attribute:name"}),
				    #"result.cad_origemleadid Expandido" = Table.ExpandTableColumn(#"result.cad_estadocivil Expandido", "result.cad_origemleadid", {"Attribute:name"}, {"Attribute:name.1"}),
				    #"Colunas Renomeadas12" = Table.RenameColumns(#"result.cad_origemleadid Expandido",{{"Attribute:name.1", "Origem Lead ID"}}),
				    #"result.crmeduc_unidade Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas12", "result.crmeduc_unidade", {"Attribute:name"}, {"Attribute:name.1"}),
				    #"Colunas Renomeadas17" = Table.RenameColumns(#"result.crmeduc_unidade Expandido",{{"Attribute:name.1", "Unidade"}}),
				    #"result.cad_dataaceitelgpd Expandido" = Table.ExpandTableColumn(#"Colunas Renomeadas17", "result.cad_dataaceitelgpd", {"Element:Text"}, {"result.cad_dataaceitelgpd.Element:Text"}),
				    #"Colunas Renomeadas13" = Table.RenameColumns(#"result.cad_dataaceitelgpd Expandido",{{"result.cad_dataaceitelgpd.Element:Text", "Data Aceite"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas13",{{"Data Aceite", type datetime}}),
				    #"result.cad_dataalteracaocadastrooferta Expandido" = Table.ExpandTableColumn(#"Tipo Alterado", "result.cad_dataalteracaocadastrooferta", {"Element:Text"}, {"result.cad_dataalteracaocadastrooferta.Element:Text"}),
				    #"Colunas Renomeadas14" = Table.RenameColumns(#"result.cad_dataalteracaocadastrooferta Expandido",{{"result.cad_dataalteracaocadastrooferta.Element:Text", "Data alteração"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas14",{{"Data alteração", type datetime}}),
				    #"result.crmeduc_tabulacaodolead Expandido" = Table.ExpandTableColumn(#"Tipo Alterado1", "result.crmeduc_tabulacaodolead", {"Attribute:name"}, {"Attribute:name.1"}),
				    #"Colunas Renomeadas15" = Table.RenameColumns(#"result.crmeduc_tabulacaodolead Expandido",{{"Attribute:name.1", "Tabulação"}, {"result.crmeduc_detalhamentotabulacao", "Tabulação Detalhe"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas15",{{"Tabulação", type text}}),
				    #"result.cad_proprietariopro Expandido" = Table.ExpandTableColumn(#"Tipo Alterado2", "result.cad_proprietariopro", {"Attribute:name"}, {"Attribute:name.1"}),
				    #"Colunas Renomeadas16" = Table.RenameColumns(#"result.cad_proprietariopro Expandido",{{"Attribute:name.1", "Proprietário Lead"}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas16",{{"Proprietário Lead", type text}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado3",{{"result.crmeduc_unidadeform", Text.Proper, type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colocar Cada Palavra Em Maiúscula","Canaa","Canaã",Replacer.ReplaceText,{"result.crmeduc_unidadeform"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído", each true),
				    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Data Criacao", type date}})
				in
				    #"Tipo Alterado6"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

