table LORENA
	isHidden
	lineageTag: 47f5f6ed-5871-438e-953b-d45975a4c1a8

	column DATA
		dataType: string
		isHidden
		lineageTag: 7d83ebaf-6e3a-4e1a-87f5-8dd90778b64a
		summarizeBy: none
		sourceColumn: DATA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		isHidden
		lineageTag: 7a31c329-d951-47d0-920b-b92bad952360
		summarizeBy: none
		sourceColumn: NOME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CELULAR
		dataType: string
		isHidden
		lineageTag: fd970093-8482-4b45-a76c-e5333fc159ef
		summarizeBy: none
		sourceColumn: CELULAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'CPF (preencher apenas com números)'
		dataType: string
		isHidden
		lineageTag: db9f2b7e-70d8-4def-bf5a-883e231880ac
		summarizeBy: none
		sourceColumn: CPF (preencher apenas com números)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CURSO
		dataType: string
		isHidden
		lineageTag: d972ed3a-06bd-4874-98a8-36ab154660ff
		summarizeBy: none
		sourceColumn: CURSO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FORMA DE INGRESSO'
		dataType: string
		isHidden
		lineageTag: fa8d0146-ccb7-4067-a951-3fc3c64f1fc4
		summarizeBy: none
		sourceColumn: FORMA DE INGRESSO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '% BOLSA CONCEDIDA'
		dataType: string
		isHidden
		lineageTag: d590cb03-27c0-4014-bef9-1f417ddf7823
		summarizeBy: none
		sourceColumn: % BOLSA CONCEDIDA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CONDIÇÃO
		dataType: string
		isHidden
		lineageTag: 8b65c50c-0c81-4d22-bbc8-51cfadb4eb4a
		summarizeBy: none
		sourceColumn: CONDIÇÃO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'VALOR PG MATRÍCULA'
		dataType: string
		isHidden
		lineageTag: cbe87770-40e1-4b99-b14f-e54f14ec7eeb
		summarizeBy: none
		sourceColumn: VALOR PG MATRÍCULA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'NOME DO PAGADOR '
		dataType: string
		isHidden
		lineageTag: ac383283-d644-4c16-a2ff-3ced4b5d9e96
		summarizeBy: none
		sourceColumn: "NOME DO PAGADOR "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FORMA DE PAGAMNTO'
		dataType: string
		isHidden
		lineageTag: e80b6a38-07ff-45eb-9238-319892ca66fc
		summarizeBy: none
		sourceColumn: FORMA DE PAGAMNTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'QUANTIDADE DE PARCELAS'
		dataType: string
		isHidden
		lineageTag: dd1e72ce-e713-4d6c-9b16-4fbcd87e1b78
		summarizeBy: none
		sourceColumn: QUANTIDADE DE PARCELAS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OBSERVAÇÃO
		dataType: string
		isHidden
		lineageTag: 6053c58a-7250-4729-87e0-9b89366b00f4
		summarizeBy: none
		sourceColumn: OBSERVAÇÃO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		isHidden
		lineageTag: b7589d2a-7f94-472e-bd9d-38d55e692f0c
		summarizeBy: none
		sourceColumn: Unidade

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data e Hora'
		dataType: string
		isHidden
		lineageTag: fe8c6537-70a3-4d45-a398-eeebfac45d19
		summarizeBy: none
		sourceColumn: Data e Hora

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'CONSULTOR (a)'
		dataType: string
		isHidden
		lineageTag: 7eb3b4d5-9f0c-4675-a39c-a6fbd57be257
		summarizeBy: none
		sourceColumn: CONSULTOR (a)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Número de Inscrição'
		dataType: string
		lineageTag: df7c0e0e-d488-4996-b48a-5be68067d737
		summarizeBy: none
		sourceColumn: Número de Inscrição

		annotation SummarizationSetBy = Automatic

	partition LORENA = m
		mode: import
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/13DBRdUsHT5wupKkq3Omi9VUr9Nj3R5gYVMfSSkmtXQM/edit?gid=0#gid=0"),
				    LORENA_Table = Fonte{[name="LORENA",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(LORENA_Table, [PromoteAllScalars=true]),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Cabeçalhos Promovidos", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Valor Substituído" = Table.TransformColumns(#"Linhas em Branco Removidas", {{"Unidade", each "Lorena", type text}})
				in
				    #"Valor Substituído"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

