table '2025-2 MED'
	lineageTag: c305dd34-7ceb-47b5-8627-616b5677c19e

	column Nome
		dataType: string
		lineageTag: 35eef536-c6e6-4c4a-b310-660ced6044a9
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Codigo
		dataType: string
		lineageTag: 156e88fe-0034-4d48-8ec3-3b0687b622e6
		summarizeBy: none
		sourceColumn: Codigo

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: a53c5f93-4077-41a4-9858-53de483c7d2f
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Celular
		dataType: string
		lineageTag: 76667727-1484-451a-9868-7836915f218c
		summarizeBy: none
		sourceColumn: Celular

		annotation SummarizationSetBy = Automatic

	column Telefone
		dataType: string
		lineageTag: f1e136a9-177b-4a13-a7cd-f6fb436a1fb8
		summarizeBy: none
		sourceColumn: Telefone

		annotation SummarizationSetBy = Automatic

	column Rg
		dataType: string
		lineageTag: 373ebbdf-4cc4-4f49-8c61-8a0f5d55e296
		summarizeBy: none
		sourceColumn: Rg

		annotation SummarizationSetBy = Automatic

	column Cpf
		dataType: string
		lineageTag: d1549362-17d2-428e-b49e-23acb926a4af
		summarizeBy: none
		sourceColumn: Cpf

		annotation SummarizationSetBy = Automatic

	column Nota
		dataType: string
		lineageTag: 769f4cae-db23-4dfd-9cc9-4f83ca669b96
		summarizeBy: none
		sourceColumn: Nota

		annotation SummarizationSetBy = Automatic

	column 'Nota Enem'
		dataType: string
		lineageTag: 7703eaf7-564e-452c-bd7d-73b6f433c528
		summarizeBy: none
		sourceColumn: Nota Enem

		annotation SummarizationSetBy = Automatic

	column 'Data Aprovacao'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0cc32e20-a749-4240-bf5f-0c1b827f6779
		summarizeBy: none
		sourceColumn: Data Aprovacao

		variation Variation
			isDefault
			relationship: 6028fce0-9767-44b6-8133-dbddfc0e1b9e
			defaultHierarchy: LocalDateTable_f10a0b2c-95c6-4e3f-bc14-b9d14ee96d76.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data Venc Matricula'
		dataType: string
		lineageTag: e985c29a-bed6-45a1-a0fa-8bca027a4ed9
		summarizeBy: none
		sourceColumn: Data Venc Matricula

		annotation SummarizationSetBy = Automatic

	column 'Data Pgto Matricula'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0014096e-815d-451e-b52e-6602a642d107
		summarizeBy: none
		sourceColumn: Data Pgto Matricula

		variation Variation
			isDefault
			relationship: 51c011f6-c583-4a49-a089-d3be8bd6f9f9
			defaultHierarchy: LocalDateTable_ea155b8b-9c16-4a5e-8a07-8aac2881b8df.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Criacao'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 693f6b55-ff25-4197-b130-441e6848a758
		summarizeBy: none
		sourceColumn: Data Criacao

		variation Variation
			isDefault
			relationship: c2452f11-8ad2-4052-a98e-9588569525f7
			defaultHierarchy: LocalDateTable_5a126e76-0c7f-4ef8-b66b-4a45484936b3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Data Atualizacao'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9afcebfa-40d1-4ec6-a23d-498083eb1a6e
		summarizeBy: none
		sourceColumn: Data Atualizacao

		variation Variation
			isDefault
			relationship: 5e9af250-5d37-415b-a9bf-be1efae9f106
			defaultHierarchy: LocalDateTable_f3033ccc-0e18-4223-9c4b-f6f275aa21cd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Termos Privacidade'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b4ed0d11-0093-413a-9028-3abffaa178e5
		summarizeBy: none
		sourceColumn: Termos Privacidade

		annotation SummarizationSetBy = Automatic

	column 'Membro Do Programa'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c85809dc-4dd9-420f-ab0a-bbde5ca3449b
		summarizeBy: none
		sourceColumn: Membro Do Programa

		annotation SummarizationSetBy = Automatic

	column 'Agendamento ID'
		dataType: string
		lineageTag: d320734a-d1eb-4178-83e0-016f3958c27e
		summarizeBy: none
		sourceColumn: Agendamento ID

		annotation SummarizationSetBy = Automatic

	column 'Concurso ID'
		dataType: string
		lineageTag: b7860447-f656-4010-87e0-ef17f77371ce
		summarizeBy: none
		sourceColumn: Concurso ID

		annotation SummarizationSetBy = Automatic

	column 'Contato ID'
		dataType: string
		lineageTag: c52ab494-666f-4ace-ad0e-ad3bbe2d850e
		summarizeBy: none
		sourceColumn: Contato ID

		annotation SummarizationSetBy = Automatic

	column 'Etapa ID'
		dataType: string
		lineageTag: b96668c8-465e-47d8-a1c2-09e55ae9e3c0
		summarizeBy: none
		sourceColumn: Etapa ID

		annotation SummarizationSetBy = Automatic

	column 'Modalidade ID'
		dataType: string
		lineageTag: 26f95f08-d0b0-49ac-ba38-df276236ab0b
		summarizeBy: none
		sourceColumn: Modalidade ID

		annotation SummarizationSetBy = Automatic

	column 'Necessidade Especial ID'
		dataType: string
		lineageTag: f9fd9302-2e5c-440e-a04a-d74312ee2cf4
		summarizeBy: none
		sourceColumn: Necessidade Especial ID

		annotation SummarizationSetBy = Automatic

	column 'Opcao De Ingresso ID'
		dataType: string
		lineageTag: 4a9f9dcb-3ca1-4455-aeda-1c00213faac6
		summarizeBy: none
		sourceColumn: Opcao De Ingresso ID

		annotation SummarizationSetBy = Automatic

	column 'Situacao ID'
		dataType: string
		lineageTag: 98b32e46-1aef-4ee5-a451-17af2d919eaa
		summarizeBy: none
		sourceColumn: Situacao ID

		annotation SummarizationSetBy = Automatic

	column 'Tipo ID'
		dataType: string
		lineageTag: 406313ff-d52a-443e-be1b-2caf6730a857
		summarizeBy: none
		sourceColumn: Tipo ID

		annotation SummarizationSetBy = Automatic

	column 'Turno ID'
		dataType: string
		lineageTag: 6cb2ddb8-36de-435a-8372-02b907dec2a8
		summarizeBy: none
		sourceColumn: Turno ID

		annotation SummarizationSetBy = Automatic

	column 'Unidade ID'
		dataType: string
		lineageTag: f8441050-9ade-4af6-8f3c-ab82d703ecf3
		summarizeBy: none
		sourceColumn: Unidade ID

		annotation SummarizationSetBy = Automatic

	column 'Operador Matricula ID'
		dataType: int64
		formatString: 0
		lineageTag: 261a5fb2-27e3-42dc-bcd6-a47574fbce25
		summarizeBy: count
		sourceColumn: Operador Matricula ID

		annotation SummarizationSetBy = Automatic

	column 'Operador Original ID'
		dataType: int64
		formatString: 0
		lineageTag: 975b9981-127b-4056-b849-8f0e1f5b92aa
		summarizeBy: count
		sourceColumn: Operador Original ID

		annotation SummarizationSetBy = Automatic

	column 'Ultimo Operador ID'
		dataType: int64
		formatString: 0
		lineageTag: 05c311f8-8482-4012-8299-9d3b6b225dfb
		summarizeBy: count
		sourceColumn: Ultimo Operador ID

		annotation SummarizationSetBy = Automatic

	column 'Data Cancel Matricula'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 982ea66a-f510-46a8-87b8-4b90b18a00bb
		summarizeBy: none
		sourceColumn: Data Cancel Matricula

		variation Variation
			isDefault
			relationship: 16743d2c-53fd-4726-9d08-192faf4306f6
			defaultHierarchy: LocalDateTable_2f9af5b1-f4ab-4be5-b265-aecb8e987c34.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Polo ID'
		dataType: string
		lineageTag: b106d321-d7b4-4eb4-abc1-1971e9d4a90f
		summarizeBy: none
		sourceColumn: Polo ID

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: 5dd0d289-9294-4959-b13a-e0de1e0ecf48
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Cep
		dataType: string
		lineageTag: 3e12d344-56a1-482f-81ed-8b83d6fbc3fc
		summarizeBy: none
		sourceColumn: Cep

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 22ea3e7e-6049-463a-b889-1d1f1fa3a235
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Endereco
		dataType: string
		lineageTag: 848da4ad-c40f-4352-81a0-4641e033986a
		summarizeBy: none
		sourceColumn: Endereco

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 5ca0e853-5a31-4087-9865-099a20e3a66c
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Numero
		dataType: int64
		formatString: 0
		lineageTag: fe67542c-ee77-4a2a-bcfa-22a66c9665cd
		summarizeBy: sum
		sourceColumn: Numero

		annotation SummarizationSetBy = Automatic

	column 'Dados Financeiros'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 41765049-a8d8-49ad-ba6d-64d21107ad32
		summarizeBy: none
		sourceColumn: Dados Financeiros

		annotation SummarizationSetBy = Automatic

	column Mensalidade
		dataType: int64
		formatString: 0
		lineageTag: ed9c85b4-105b-433f-9f37-efc988048a3a
		summarizeBy: sum
		sourceColumn: Mensalidade

		annotation SummarizationSetBy = Automatic

	column 'Data Integracao'
		dataType: string
		lineageTag: 02be78d0-58c9-4813-b7e7-47bc85de26e7
		summarizeBy: none
		sourceColumn: Data Integracao

		annotation SummarizationSetBy = Automatic

	column 'Ano Enem'
		dataType: string
		lineageTag: 6ce1bcc7-8384-4a13-80c8-c01affc07d3c
		summarizeBy: none
		sourceColumn: Ano Enem

		annotation SummarizationSetBy = Automatic

	column 'Codigo Anterior'
		dataType: string
		lineageTag: e9ba206f-37b0-42f0-99db-fc9ad176f699
		summarizeBy: none
		sourceColumn: Codigo Anterior

		annotation SummarizationSetBy = Automatic

	column 'Codigo Interno'
		dataType: string
		lineageTag: 22611508-4288-4f11-bef5-049435b652f3
		summarizeBy: none
		sourceColumn: Codigo Interno

		annotation SummarizationSetBy = Automatic

	column 'Curso Anterior'
		dataType: string
		lineageTag: db3f9c1b-2e87-4d9e-a401-a7f6e914a673
		summarizeBy: none
		sourceColumn: Curso Anterior

		annotation SummarizationSetBy = Automatic

	column 'Instituicao Anterior'
		dataType: string
		lineageTag: d005599a-bd1b-4d8c-99ea-d707d220d2ca
		summarizeBy: none
		sourceColumn: Instituicao Anterior

		annotation SummarizationSetBy = Automatic

	column Modificado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 56690a0f-4cf7-425d-9885-29f80e6e43d2
		summarizeBy: none
		sourceColumn: Modificado

		annotation SummarizationSetBy = Automatic

	column Documentacao
		dataType: string
		lineageTag: f82cea26-c83c-44c5-865d-11dbb0dfd90d
		summarizeBy: none
		sourceColumn: Documentacao

		annotation SummarizationSetBy = Automatic

	column 'Matricula Academica'
		dataType: string
		lineageTag: b9ea1dbb-d261-4e41-b4e8-06c51f41716f
		summarizeBy: none
		sourceColumn: Matricula Academica

		annotation SummarizationSetBy = Automatic

	column 'Valor Pago Matricula'
		dataType: string
		lineageTag: 6c5d8822-2bbe-4e6f-8ab7-cee3894a7c9f
		summarizeBy: none
		sourceColumn: Valor Pago Matricula

		annotation SummarizationSetBy = Automatic

	column 'Data Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06549e8f-66c9-4516-92ee-4730202c30de
		summarizeBy: none
		sourceColumn: Data Nascimento

		variation Variation
			isDefault
			relationship: add19281-4e8d-4cbf-a5e1-8985df9643e0
			defaultHierarchy: LocalDateTable_6d82a70a-7540-4cc5-95b6-b238837c3c8c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Estado Civil'
		dataType: string
		lineageTag: bf7ddbce-9040-4410-82be-903863b8c0ce
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 43966a2c-6698-489a-a12d-a01234f801a8
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Codigo Ibge ID'
		dataType: int64
		formatString: 0
		lineageTag: 0d0bc83e-6be0-4787-968d-0aabe44a8e89
		summarizeBy: count
		sourceColumn: Codigo Ibge ID

		annotation SummarizationSetBy = Automatic

	column 'Valor Orig Matricula'
		dataType: string
		lineageTag: ffb70556-3929-446b-a5bb-37aaf26383b7
		summarizeBy: none
		sourceColumn: Valor Orig Matricula

		annotation SummarizationSetBy = Automatic

	column 'Opcao De Curso ID'
		dataType: int64
		formatString: 0
		lineageTag: 55ccf5bd-01d7-4256-9b31-d4300418adb7
		summarizeBy: count
		sourceColumn: Opcao De Curso ID

		annotation SummarizationSetBy = Automatic

	column 'Rg Data Expedicao'
		dataType: string
		lineageTag: 6d085735-7072-491f-955e-575252abdb39
		summarizeBy: none
		sourceColumn: Rg Data Expedicao

		annotation SummarizationSetBy = Automatic

	column 'Rg Emissor'
		dataType: string
		lineageTag: 470e1e46-af3b-4951-8291-9a3df5a05469
		summarizeBy: none
		sourceColumn: Rg Emissor

		annotation SummarizationSetBy = Automatic

	column 'Rg Uf'
		dataType: string
		lineageTag: 455bacdb-7107-4a10-b92b-701bad2c0237
		summarizeBy: none
		sourceColumn: Rg Uf

		annotation SummarizationSetBy = Automatic

	column 'URL Portal'
		dataType: string
		lineageTag: bca6194d-600f-476e-8559-bed56ff8a3dd
		summarizeBy: none
		sourceColumn: URL Portal

		annotation SummarizationSetBy = Automatic

	column 'Tipo Produto ID'
		dataType: string
		lineageTag: f6c6fc46-2f1e-40da-9961-0bcc3ffe8949
		summarizeBy: none
		sourceColumn: Tipo Produto ID

		annotation SummarizationSetBy = Automatic

	column 'Pontuacao Anterior'
		dataType: int64
		formatString: 0
		lineageTag: 4cd135e3-d243-4fe6-abb9-4575a84bf114
		summarizeBy: sum
		sourceColumn: Pontuacao Anterior

		annotation SummarizationSetBy = Automatic

	column 'Pontuacao Diaria'
		dataType: int64
		formatString: 0
		lineageTag: 2cf89269-5503-4d6e-a8dd-7567d6ae7f9d
		summarizeBy: sum
		sourceColumn: Pontuacao Diaria

		annotation SummarizationSetBy = Automatic

	column 'Pontuacao Fim Semana'
		dataType: int64
		formatString: 0
		lineageTag: 99af8ba3-998b-4a40-b9e2-c06fec845308
		summarizeBy: sum
		sourceColumn: Pontuacao Fim Semana

		annotation SummarizationSetBy = Automatic

	column 'Pontuacao Inicial'
		dataType: int64
		formatString: 0
		lineageTag: 382f7cba-08ec-4097-ad17-363cf343bb61
		summarizeBy: sum
		sourceColumn: Pontuacao Inicial

		annotation SummarizationSetBy = Automatic

	column 'Pontuacao Inicio Semana'
		dataType: int64
		formatString: 0
		lineageTag: c0a24d10-9104-46ed-9178-b6f60bb6f5ff
		summarizeBy: sum
		sourceColumn: Pontuacao Inicio Semana

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Bairro'
		dataType: string
		lineageTag: 9e5b1b49-3ee7-474a-9cd8-c9c45be4155b
		summarizeBy: none
		sourceColumn: Responsavel Bairro

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Celular'
		dataType: int64
		formatString: 0
		lineageTag: 063affb8-c881-4956-ae14-ecaa0659b7ad
		summarizeBy: sum
		sourceColumn: Responsavel Celular

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Cep'
		dataType: string
		lineageTag: ecd23a35-ab0b-469d-87e2-217e35594cab
		summarizeBy: none
		sourceColumn: Responsavel Cep

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Cidade'
		dataType: string
		lineageTag: 87f1e41f-8c2d-4c88-9591-043e8c370cb5
		summarizeBy: none
		sourceColumn: Responsavel Cidade

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Complemento'
		dataType: string
		lineageTag: aa1841b4-fae1-4643-a50c-a5b9ab8fd99f
		summarizeBy: none
		sourceColumn: Responsavel Complemento

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Documento'
		dataType: string
		lineageTag: 94eacfb0-c91b-4e32-961a-bfb6e77cc722
		summarizeBy: none
		sourceColumn: Responsavel Documento

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Email'
		dataType: string
		lineageTag: a74f0880-46fc-407a-87e1-b5e309509a8b
		summarizeBy: none
		sourceColumn: Responsavel Email

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Estado'
		dataType: string
		lineageTag: ca4dda5c-3c26-4c9d-b731-bef11ca0d8c4
		summarizeBy: none
		sourceColumn: Responsavel Estado

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Nome'
		dataType: string
		lineageTag: d711e95d-90b0-4d5b-a96b-34567ed03d87
		summarizeBy: none
		sourceColumn: Responsavel Nome

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Numero'
		dataType: int64
		formatString: 0
		lineageTag: fc43c485-69b7-4dd8-8f1e-4ddf108e96f7
		summarizeBy: sum
		sourceColumn: Responsavel Numero

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Pais'
		dataType: string
		lineageTag: 31d56eb2-3cd1-4a53-bf3c-36d4321723f1
		summarizeBy: none
		sourceColumn: Responsavel Pais

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Rua'
		dataType: string
		lineageTag: af136833-754c-42f9-b7a8-2429d92cc3c7
		summarizeBy: none
		sourceColumn: Responsavel Rua

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Tipo Documento'
		dataType: string
		lineageTag: 69ba2134-2262-40e6-9b6b-3df2a50c9a28
		summarizeBy: none
		sourceColumn: Responsavel Tipo Documento

		annotation SummarizationSetBy = Automatic

	column Treineiro
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 14ddad96-91d9-4a2d-a62b-798897970463
		summarizeBy: none
		sourceColumn: Treineiro

		annotation SummarizationSetBy = Automatic

	column 'Etapa Integracao'
		dataType: string
		lineageTag: 3640b62b-7ed3-4bfb-ae8d-4543428d3d65
		summarizeBy: none
		sourceColumn: Etapa Integracao

		annotation SummarizationSetBy = Automatic

	column 'Integracao Finalizada'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 105896d4-f83e-42a6-a7ab-e6626da44154
		summarizeBy: none
		sourceColumn: Integracao Finalizada

		annotation SummarizationSetBy = Automatic

	column 'Segunda Opcao ID'
		dataType: string
		lineageTag: 45947e4d-2b96-408c-aac3-db8ec743d8f6
		summarizeBy: none
		sourceColumn: Segunda Opcao ID

		annotation SummarizationSetBy = Automatic

	column 'Turno Segunda Opcao ID'
		dataType: string
		lineageTag: 4a52e828-94a8-4171-a4e4-31a6c31f2fd1
		summarizeBy: none
		sourceColumn: Turno Segunda Opcao ID

		annotation SummarizationSetBy = Automatic

	column 'Data Etapa Aprovado'
		dataType: dateTime
		formatString: General Date
		lineageTag: aa6c1ef8-2e75-483f-9a27-06efc7d5f843
		summarizeBy: none
		sourceColumn: Data Etapa Aprovado

		variation Variation
			isDefault
			relationship: 4fcf9589-895e-40b9-8a32-aa69cf4168a6
			defaultHierarchy: LocalDateTable_d17f78b0-8aaa-41e9-818f-63f8d2c6077d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: ae818a2e-1eb3-4043-9c8c-3b47bd1f0e9c
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column Observacoes
		dataType: string
		lineageTag: 16666ae9-9fc6-42d7-9389-d3d5af8e6661
		summarizeBy: none
		sourceColumn: Observacoes

		annotation SummarizationSetBy = Automatic

	column 'Eh Medico'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 32411d2e-2b5b-47d2-8833-f29ab859bfef
		summarizeBy: none
		sourceColumn: Eh Medico

		annotation SummarizationSetBy = Automatic

	column 'Etapa Carreira Medica'
		dataType: string
		lineageTag: fddc8c7e-9d01-4223-8ccc-fa24216a20c9
		summarizeBy: none
		sourceColumn: Etapa Carreira Medica

		annotation SummarizationSetBy = Automatic

	column 'Curso Destino ID'
		dataType: string
		lineageTag: 0125528e-0af2-4ecf-ad99-b6d2494ad3ba
		summarizeBy: none
		sourceColumn: Curso Destino ID

		annotation SummarizationSetBy = Automatic

	column 'Curso Origem'
		dataType: string
		lineageTag: b76e9b8d-b421-477f-acd3-1ea36e3f53c8
		summarizeBy: none
		sourceColumn: Curso Origem

		annotation SummarizationSetBy = Automatic

	column 'Periodo Destino'
		dataType: int64
		formatString: 0
		lineageTag: 6a746c4d-ae00-45cc-995a-26350d50881a
		summarizeBy: sum
		sourceColumn: Periodo Destino

		annotation SummarizationSetBy = Automatic

	column 'Ano Ensino Medio'
		dataType: string
		lineageTag: f0b99175-ba5c-42c7-ac1d-26f40279be05
		summarizeBy: none
		sourceColumn: Ano Ensino Medio

		annotation SummarizationSetBy = Automatic

	column 'Instituicao Ensino Medio ID'
		dataType: string
		lineageTag: 7abf3116-e8cd-4c11-87eb-9b9060ef739e
		summarizeBy: none
		sourceColumn: Instituicao Ensino Medio ID

		annotation SummarizationSetBy = Automatic

	column 'Nome Mae'
		dataType: string
		lineageTag: cf95d80d-af60-47b1-b541-e9e416ca2f44
		summarizeBy: none
		sourceColumn: Nome Mae

		annotation SummarizationSetBy = Automatic

	column 'Nome Pai'
		dataType: string
		lineageTag: dfd97e7c-5785-42a5-aea8-e56ffed8dd0a
		summarizeBy: none
		sourceColumn: Nome Pai

		annotation SummarizationSetBy = Automatic

	column 'Cor Raca ID'
		dataType: string
		lineageTag: 7613a2f2-662d-4e0a-a268-006a926a74e5
		summarizeBy: none
		sourceColumn: Cor Raca ID

		annotation SummarizationSetBy = Automatic

	column 'Numero Inscricao Enem'
		dataType: string
		lineageTag: 0d837060-3fb3-4183-802a-6eaf6c2ea19f
		summarizeBy: none
		sourceColumn: Numero Inscricao Enem

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: 20932d4c-1e2f-4d7c-9008-21ab0658a0e3
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	column Scoring
		dataType: int64
		formatString: 0
		lineageTag: 711935f1-cb81-4715-9d87-10d99da30ffe
		summarizeBy: sum
		sourceColumn: Scoring

		annotation SummarizationSetBy = Automatic

	column 'Data Pgto Inscricao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6559c3d4-469a-49a2-9bbb-c6abe13f7922
		summarizeBy: none
		sourceColumn: Data Pgto Inscricao

		variation Variation
			isDefault
			relationship: 1c0643bc-4afb-4a99-a37a-2946fbd94e61
			defaultHierarchy: LocalDateTable_a2022c07-6fc4-4b18-8e34-a06c2bf30c75.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ne Acompanhamento'
		dataType: string
		lineageTag: fd7857ec-747a-43bc-ba09-d583d1a40203
		summarizeBy: none
		sourceColumn: Ne Acompanhamento

		annotation SummarizationSetBy = Automatic

	column 'Ne Codigo Cid'
		dataType: string
		lineageTag: fb65181f-cd64-4235-8273-bdbfb3a85e78
		summarizeBy: none
		sourceColumn: Ne Codigo Cid

		annotation SummarizationSetBy = Automatic

	column 'Ne Medicos'
		dataType: string
		lineageTag: c5464b27-6f05-4dfd-907a-3f349707f72d
		summarizeBy: none
		sourceColumn: Ne Medicos

		annotation SummarizationSetBy = Automatic

	column 'Ne Obs'
		dataType: string
		lineageTag: fd2790d3-8066-465e-afa5-612ee48b41c8
		summarizeBy: none
		sourceColumn: Ne Obs

		annotation SummarizationSetBy = Automatic

	column 'Inscrito Avaliado ID'
		dataType: string
		lineageTag: 2023d073-478c-4f8e-a83b-b5b4dffe931a
		summarizeBy: none
		sourceColumn: Inscrito Avaliado ID

		annotation SummarizationSetBy = Automatic

	column 'Nota Reaproveitada'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f548244-57ad-4f1e-a4b5-93e36a92faa8
		summarizeBy: none
		sourceColumn: Nota Reaproveitada

		annotation SummarizationSetBy = Automatic

	column 'Contato Interno'
		dataType: string
		lineageTag: a7850ede-c381-4ad3-bceb-5bb3aaff9187
		summarizeBy: none
		sourceColumn: Contato Interno

		annotation SummarizationSetBy = Automatic

	column 'Inscrito Interno'
		dataType: string
		lineageTag: 8cfbd56e-df94-4be3-a994-da8cd0f84895
		summarizeBy: none
		sourceColumn: Inscrito Interno

		annotation SummarizationSetBy = Automatic

	column Duracao
		dataType: string
		lineageTag: fc750d56-2e2d-4366-b14c-4f8a7ad6fce5
		summarizeBy: none
		sourceColumn: Duracao

		annotation SummarizationSetBy = Automatic

	column Duplicada
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: da3f3611-8e82-4fb8-ae0b-d4b716b651da
		summarizeBy: none
		sourceColumn: Duplicada

		annotation SummarizationSetBy = Automatic

	column 'Contrato Interno'
		dataType: string
		lineageTag: 765c04d2-7a51-40a0-bfb1-d46d360ea737
		summarizeBy: none
		sourceColumn: Contrato Interno

		annotation SummarizationSetBy = Automatic

	column 'Aprovacao Automatica'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e7000751-ef5d-4032-b2f9-6b92b638cfd5
		summarizeBy: none
		sourceColumn: Aprovacao Automatica

		annotation SummarizationSetBy = Automatic

	column 'Legenda Scoring'
		dataType: string
		lineageTag: 00f5c783-56c6-402d-aa6d-009f146b0bb9
		summarizeBy: none
		sourceColumn: Legenda Scoring

		annotation SummarizationSetBy = Automatic

	column 'Nacionalidade ID'
		dataType: string
		lineageTag: 8ae17ef2-d7b1-4de0-a29c-90ff90c151eb
		summarizeBy: none
		sourceColumn: Nacionalidade ID

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Nacionalidade ID'
		dataType: string
		lineageTag: 2937b568-a66d-4471-b1b7-88ebca9fc4cd
		summarizeBy: none
		sourceColumn: Responsavel Nacionalidade ID

		annotation SummarizationSetBy = Automatic

	column 'Vinculo ID'
		dataType: string
		lineageTag: 2f5ca002-0293-4100-b950-84444e9df3ed
		summarizeBy: none
		sourceColumn: Vinculo ID

		annotation SummarizationSetBy = Automatic

	column 'Data Venc Inscricao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a30ddd36-cfc8-4cce-b593-3ebdd734b65b
		summarizeBy: none
		sourceColumn: Data Venc Inscricao

		variation Variation
			isDefault
			relationship: 9bed66af-6b97-47be-a66b-74ffdbcb4683
			defaultHierarchy: LocalDateTable_c2852a58-0615-4708-8686-72fc571b3767.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Referer
		dataType: string
		lineageTag: ddda2e47-c184-4bb3-adbe-55e5936a434b
		summarizeBy: none
		sourceColumn: Referer

		annotation SummarizationSetBy = Automatic

	column 'User Agent'
		dataType: string
		lineageTag: dcad20a3-79a8-4cb0-9e0e-1eb2b82fe011
		summarizeBy: none
		sourceColumn: User Agent

		annotation SummarizationSetBy = Automatic

	column 'Valor Orig Inscricao'
		dataType: double
		lineageTag: 6a6b6699-75e4-434a-8680-b9815f909ad7
		summarizeBy: sum
		sourceColumn: Valor Orig Inscricao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valor Pago Inscricao'
		dataType: double
		lineageTag: 5b606efe-33af-4157-9917-e723c108c075
		summarizeBy: sum
		sourceColumn: Valor Pago Inscricao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Responsavel Cor Raca ID'
		dataType: string
		lineageTag: 56ecce89-a246-4424-9b94-9c35bfccee6d
		summarizeBy: none
		sourceColumn: Responsavel Cor Raca ID

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Dt Nasc'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9aad0beb-f36b-42b0-96af-bcd926b7e70a
		summarizeBy: none
		sourceColumn: Responsavel Dt Nasc

		variation Variation
			isDefault
			relationship: 20ec1e85-f2c6-4d3c-969c-a90a06da3e76
			defaultHierarchy: LocalDateTable_00294117-a5bd-4aa2-add5-299c708d964e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Responsavel Est Civil'
		dataType: string
		lineageTag: 09fee0f3-c8f0-4942-85e3-20be3115e4c8
		summarizeBy: none
		sourceColumn: Responsavel Est Civil

		annotation SummarizationSetBy = Automatic

	column 'Responsavel Sexo'
		dataType: string
		lineageTag: b5342005-ee09-4355-b1a4-e4410c18f4fc
		summarizeBy: none
		sourceColumn: Responsavel Sexo

		annotation SummarizationSetBy = Automatic

	column 'Data Efetiv Matricula'
		dataType: string
		lineageTag: 2f1f0d4c-6f42-43a6-b536-94dd82ebb748
		summarizeBy: none
		sourceColumn: Data Efetiv Matricula

		annotation SummarizationSetBy = Automatic

	column 'Data Aceite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3f35dbcf-5482-4901-8d36-bf6bdabd477b
		summarizeBy: none
		sourceColumn: Data Aceite

		variation Variation
			isDefault
			relationship: 132adc48-5331-46ae-b5fe-563ef1596389
			defaultHierarchy: LocalDateTable_b2bcd7ff-95af-42fa-846b-58e0d7de4db6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 172ae879-e925-4ce3-9626-297c5108f641
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column 'Esta Empregado'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 018bd66b-f8dd-4058-9f38-eca98ea14e0b
		summarizeBy: none
		sourceColumn: Esta Empregado

		annotation SummarizationSetBy = Automatic

	column 'Rg Orgao Emissor ID'
		dataType: string
		lineageTag: 24787648-2f37-4747-aa22-dce656c403b0
		summarizeBy: none
		sourceColumn: Rg Orgao Emissor ID

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: c1572f3f-5b29-4b8d-9846-6c9c85cb9619
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: fbe6d66a-7e79-4fbe-b2a2-963b5ea5adf2
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column UnidadeEditada
		dataType: string
		lineageTag: 050ebb79-dd3a-406a-83b9-745759ead9fb
		summarizeBy: none
		sourceColumn: UnidadeEditada

		annotation SummarizationSetBy = Automatic

	column 'Data Aprovação Presente'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba0e30c3-731e-48c1-b73e-8f2c9cdc6e1b
		summarizeBy: none
		sourceColumn: Data Aprovação Presente

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Pgto Matricula Presente'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 82097214-ff42-4f69-ae32-d93268ecb07c
		summarizeBy: none
		sourceColumn: Data Pgto Matricula Presente

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Criacao Presente'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 260cb9e9-291c-4e80-8793-f8e1585b8ffa
		summarizeBy: none
		sourceColumn: Data Criacao Presente

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Pgto Inscricao Presente'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 01af0658-0a50-40da-9b30-f1173b5b53ba
		summarizeBy: none
		sourceColumn: Data Pgto Inscricao Presente

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition '2025-2 MED' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(
				    Web.Contents(
				        "https://grupoeducacionalsantoant.sharepoint.com/Shared%20Documents/Arquivos%20diversos/BI/BI%20-%20Ingresso%20Inscrito%202025.2%20-%20Medicina.xlsx"
				    ),
				    null,
				    true
				),
				    #"Resultado da consulta_Sheet" = Fonte{[Item="Resultado da consulta",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Resultado da consulta_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Nome", type text}, {"Codigo", type text}, {"Email", type text}, {"Celular", type text}, {"Telefone", type text}, {"Rg", type text}, {"Cpf", type text}, {"Nota", type any}, {"Nota Enem", type any}, {"Data Aprovacao", type datetime}, {"Data Venc Matricula", type any}, {"Data Pgto Matricula", type date}, {"Data Criacao", type datetime}, {"Data Atualizacao", type datetime}, {"Termos Privacidade", type logical}, {"Membro Do Programa", type logical}, {"Agendamento ID", type any}, {"Concurso ID", type text}, {"Contato ID", type text}, {"Curso ID", type text}, {"Etapa ID", type text}, {"Modalidade ID", type text}, {"Necessidade Especial ID", type text}, {"Opcao De Ingresso ID", type text}, {"Situacao ID", type text}, {"Tipo ID", type text}, {"Turno ID", type text}, {"Unidade ID", type text}, {"Operador Matricula ID", Int64.Type}, {"Operador Original ID", Int64.Type}, {"Ultimo Operador ID", Int64.Type}, {"Data Cancel Matricula", type date}, {"Polo ID", type any}, {"Bairro", type text}, {"Cep", type text}, {"Cidade", type text}, {"Endereco", type text}, {"Estado", type text}, {"Numero", Int64.Type}, {"Dados Financeiros", type logical}, {"Mensalidade", Int64.Type}, {"Data Integracao", type any}, {"Ano Enem", type any}, {"Codigo Anterior", type any}, {"Codigo Interno", type any}, {"Curso Anterior", type any}, {"Instituicao Anterior", type any}, {"Modificado", type logical}, {"Documentacao", type text}, {"Matricula Academica", type any}, {"Valor Pago Matricula", type any}, {"Data Nascimento", type date}, {"Estado Civil", type text}, {"Sexo", type text}, {"Codigo Ibge ID", Int64.Type}, {"Valor Orig Matricula", type any}, {"Opcao De Curso ID", Int64.Type}, {"Rg Data Expedicao", type any}, {"Rg Emissor", type text}, {"Rg Uf", type text}, {"URL Portal", type any}, {"Tipo Produto ID", type text}, {"Pontuacao Anterior", Int64.Type}, {"Pontuacao Diaria", Int64.Type}, {"Pontuacao Fim Semana", Int64.Type}, {"Pontuacao Inicial", Int64.Type}, {"Pontuacao Inicio Semana", Int64.Type}, {"Responsavel Bairro", type text}, {"Responsavel Celular", Int64.Type}, {"Responsavel Cep", type text}, {"Responsavel Cidade", type text}, {"Responsavel Complemento", type text}, {"Responsavel Documento", type text}, {"Responsavel Email", type text}, {"Responsavel Estado", type text}, {"Responsavel Nome", type text}, {"Responsavel Numero", Int64.Type}, {"Responsavel Pais", type text}, {"Responsavel Rua", type text}, {"Responsavel Tipo Documento", type text}, {"Treineiro", type logical}, {"Etapa Integracao", type any}, {"Integracao Finalizada", type logical}, {"Segunda Opcao ID", type any}, {"Turno Segunda Opcao ID", type any}, {"Data Etapa Aprovado", type datetime}, {"Complemento", type text}, {"Observacoes", type text}, {"Eh Medico", type logical}, {"Etapa Carreira Medica", type any}, {"Curso Destino ID", type text}, {"Curso Origem", type text}, {"Periodo Destino", Int64.Type}, {"Ano Ensino Medio", type any}, {"Instituicao Ensino Medio ID", type any}, {"Nome Mae", type text}, {"Nome Pai", type text}, {"Cor Raca ID", type text}, {"Numero Inscricao Enem", type any}, {"UUID", type text}, {"Scoring", Int64.Type}, {"Data Pgto Inscricao", type date}, {"Ne Acompanhamento", type text}, {"Ne Codigo Cid", type text}, {"Ne Medicos", type text}, {"Ne Obs", type text}, {"Inscrito Avaliado ID", type any}, {"Nota Reaproveitada", type logical}, {"Contato Interno", type any}, {"Inscrito Interno", type any}, {"Duracao", type any}, {"Duplicada", type logical}, {"Contrato Interno", type any}, {"Aprovacao Automatica", type logical}, {"Legenda Scoring", type text}, {"Nacionalidade ID", type text}, {"Responsavel Nacionalidade ID", type text}, {"Vinculo ID", type any}, {"Data Venc Inscricao", type date}, {"Referer", type text}, {"User Agent", type text}, {"Valor Orig Inscricao", type number}, {"Valor Pago Inscricao", type number}, {"Responsavel Cor Raca ID", type text}, {"Responsavel Dt Nasc", type date}, {"Responsavel Est Civil", type text}, {"Responsavel Sexo", type text}, {"Data Efetiv Matricula", type any}, {"Data Aceite", type datetime}, {"Empresa", type any}, {"Esta Empregado", type logical}, {"Rg Orgao Emissor ID", type any}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Tipo Alterado", "Curso ID", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, true), {"Curso ID.1", "Curso ID.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Curso ID.1", type text}, {"Curso ID.2", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Curso ID.1", "Curso"}, {"Curso ID.2", "Unidade"}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Colunas Renomeadas",{{"Unidade", Text.Proper, type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "UnidadeEditada", each let
				    DDDAltamira = {"93","77","81","85","91","94","98"},
				    DDDLorena   = {"31","35","11","12","21","24","27","41","44","55","61","66", "16", "19", "37" },
				    DDD = Text.Middle([Celular], 3, 2)
				in
				    if [Unidade] <> "Ambas" then
				        [Unidade]
				    else if List.Contains(DDDAltamira, DDD) then
				        "Altamira"
				    else if List.Contains(DDDLorena, DDD) then
				        "Lorena"
				    else
				        [Unidade]),
				    Personalizar4 = Table.AddColumn(
				    #"Personalização Adicionada",
				    "Data Criacao Presente",
				    each Date.AddYears([Data Criacao], 1)
				),
				    Personalizar2 = Table.AddColumn(Personalizar4, "Data Aprovação Presente", each Date.AddYears([Data Aprovacao],1)),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(Personalizar2,{{"Data Aprovação Presente", type date}}),
				    Personalizar3 = Table.AddColumn(#"Tipo Alterado2", "Data Pgto Matricula Presente", each Date.AddYears([Data Pgto Matricula],1)),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(Personalizar3,{{"Data Pgto Matricula Presente", type date}, {"Data Criacao Presente", type date}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado3", "Data Pgto Inscricao Presente", each Date.AddYears([Data Pgto Inscricao], 1)),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Data Pgto Inscricao Presente", type date}})
				in
				    #"Tipo Alterado4"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

