table 'Metas - Medicina'
	lineageTag: 6704e7fb-7d7b-45fd-b078-e3ebff4f83b8

	column Unidade
		dataType: string
		lineageTag: e23b933e-9786-4646-a097-8eb2f9852dc4
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column 'Forma de Ingresso'
		dataType: string
		lineageTag: 89de2160-93d4-4e97-a069-4e7e71821733
		summarizeBy: none
		sourceColumn: Forma de Ingresso

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 8ad35995-c8e5-4a8c-b66a-fb7d1cead944
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0015a8d7-5ee3-4777-a1d8-26e41abaa7bb
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 657648a2-73af-49d6-bebb-1405e3b1b0ef
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	partition 'Metas - Medicina' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://grupoeducacionalsantoant.sharepoint.com/sites/TriventoEducaco/Documentos Compartilhados/Metas 2026.2 - Medicina.xlsx"), null, true),
				    #"distribuicao_2026-2_valores_Sheet" = Fonte{[Item="distribuicao_2026-2_valores",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"distribuicao_2026-2_valores_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Unidade", type text}, {"Forma de Ingresso", type text}, {"Etapa", type text}, {"Data", type date}, {"Quantidade", Int64.Type}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"Etapa", Order.Ascending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

