table 'Metas Curso'
	lineageTag: 6b14124a-4458-4130-aa8d-7112d0e84aa2

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 8d82b191-da75-48ca-b415-024a37945168
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 744da160-b8ef-44c7-b785-f7592eade487
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column Curso
		dataType: string
		lineageTag: f3374722-4d92-4c6d-ae54-301f93bb907e
		summarizeBy: none
		sourceColumn: Curso

		annotation SummarizationSetBy = Automatic

	column Meta
		dataType: int64
		formatString: 0
		lineageTag: 7d2f1545-8364-439f-aa7d-b9cdb55de45f
		summarizeBy: sum
		sourceColumn: Meta

		annotation SummarizationSetBy = Automatic

	column 'Unidade Curso'
		dataType: string
		lineageTag: ef1e37fe-4b1f-458c-b92e-11bd0f740bfc
		summarizeBy: none
		sourceColumn: Unidade Curso

		annotation SummarizationSetBy = Automatic

	partition 'Metas Curso' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZRNbsIwEIWvEmXNok5sfpZtgapS/6Sq3SAWhrjpSHHcOob7oC666ilysZrYgMdA1Z0F37w38+LxbJaStJdeVoZL0Hx7LCTU0BjN2+/2S9lfSD+d92ZpZo+3hi9Ag1GnwYsOzO3xTmlR/ylHI9u63VTQiEQkY9GIeq2qNUhRG5UUInm2CkLyZluedeV9ZPLf4tx1OIi8S61qJWF7zkYdMULy+nMFRpiV5tbhRS+4nUgGs9jBkeAVKCkKWEJXTp0pIVGAmPKtkSx0Pi0URTcGLZwiYw5gkdOB2Lmg+AIB//cwEpgUq6X7gMm0/WlguS3zZiiqkyBxZBalNKnfhJa8FPLQWBaHhKDMQygjTHirPLYqRf3ONfDkGtZQBSQ9MjxCbeAdyrDtOck8jn/KtWw3SziElvdxfyGxUxmEbgggDhhGGtCAMkLzD0e5PclHcTMY89+GXiA3zPh7R0nI3HC71Pu1IW5tKA2Re391k1dhxcAuqe7gvhuAMjzAOTx3k9Aos4eV0bB/VPwYg2haDPk5hmGTiNhZjbDVY6HsW1KpMoyDocgw4i8qi97WJ7sQe8bvGovfVQy5uRh6U4+I+S8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Unidade = _t, Curso = _t, Meta = _t]),
				
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ID", Int64.Type}, {"Curso", type text}, {"Unidade", type text}, {"Meta", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Unidade Curso", each [Unidade] & "-" & [Curso])
				in
				    #"Personalização Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

